### ISSUE TITLE
사용자 기능

### ISSUE THREAD

**Issue by rnin9** [rnin9/KT-ds-University-17th-web-application-project#1]
사용자 요구사항에 관련된 issue입니다.

**Comment by EunjinKwon** [comment]
사용자에 관련된 Relation입니다.

**Comment by EunjinKwon** [comment]
사용자에 관련된 Relation입니다.

**Comment by EunjinKwon** [comment]
## 메인 페이지
###### -편의를 위해 상단,본문,하단으로 나누어 기능 작성 하였습니다.
###### -카테고리 관련 이슈는 다음 글로 올리겠습니다.

### 상단메뉴
+ 현재 홈/로그인/사이트맵/고대비모드 등등.. 에서 로그인/회원가입 으로 기능 축소
  + 로그인 전(로그인|회원가입)
![beforelogin](https://user-images.githubusercontent.com/77440874/108948725-60771e00-76a6-11eb-9654-1a871586ced3.PNG)
  + 로그인 후(ㅇㅇㅇ님|로그아웃)
![afterlogin](https://user-images.githubusercontent.com/77440874/108953300-52c59680-76ae-11eb-8946-3d4f997808ce.PNG)
  + 이름을 클릭하면 마이 페이지로 이동

#### 로그인
+ 아이디 찾기
  + 아이디를 찾을 때 휴대전화 본인 인증으로 가능
+ 비밀번호 찾기
  + 사용자가 비밀번호를 직접 찾을 수 있게 **_-> kt 보안 정책에 괜찮나요?_**

#### 회원가입
+ SNS 간편 가입 **_->이것도 보안 상 (구현 후 사용이) 가능한지 알아봐야 할 듯_**
+ 회원 정보 입력
  + 휴대전화 인증 기능 추가

#### 마이페이지
+ 지원 현황
  + 지원서 관리 및 제출 현황, 결과 확인
+ 수강 강의 확인
  + 수강 중/수강 완료한 강의, 수강 후기 작성
  + 강의 평가는 종이로 해야 한다고 하셨어서 구현하지 않아도 될 듯

***

### 본문
+ 지원페이지 이동
  + 접수 진행 중인 강좌들을 각각 이미지로 만들어서, 해당 이미지를 클릭하면 지원페이지로 바로 이동하는 기능
  + 지원페이지로 이동 후, 지원하는 강좌가 자동으로 선택

***

### 하단
+ 홈페이지 링크 공유
  + 공유 아이콘 추가(카카오톡, 카카오스토리, 트위터, 라인, 밴드, 블로그)


***
###### 추가하거나 수정할 기능, 내용들 코멘트 부탁드립니다

**Comment by rnin9** [comment]
> #### 로그인
> * 아이디 찾기
>   
>   * 아이디를 찾을 때 휴대전화 본인 인증으로 가능
> * 비밀번호 찾기
>   
>   * 사용자가 비밀번호를 직접 찾을 수 있게 **_-> kt 보안 정책에 괜찮나요?_**
> 
> #### 회원가입
> * SNS 간편 가입 **_->이것도 보안 상 (구현 후 사용이) 가능한지 알아봐야 할 듯_**
> * 회원 정보 입력
>   
>   * 휴대전화 인증 기능 추가
> 
> #### 마이페이지
> * 지원 현황
>   
>   * 지원서 관리 및 제출 현황, 결과 확인
> * 수강 강의 확인
>   
>   * 수강 중/수강 완료한 강의, 수강 후기 작성
>   * 강의 평가는 종이로 해야 한다고 하셨어서 구현하지 않아도 될 듯
> 
> ### 본문
> * 지원페이지 이동
>   
>   * 접수 진행 중인 강좌들을 각각 이미지로 만들어서, 해당 이미지를 클릭하면 지원페이지로 바로 이동하는 기능
>   * 지원페이지로 이동 후, 지원하는 강좌가 자동으로 선택
> 
> ### 하단
> * 홈페이지 링크 공유
>   
>   * 공유 아이콘 추가(카카오톡, 카카오스토리, 트위터, 라인, 밴드, 블로그)
> 
> ###### 추가하거나 수정할 기능, 내용들 코멘트 부탁드립니다

**Comment by rnin9** [comment]
> #### 로그인
> * 아이디 찾기
>   
>   * 아이디를 찾을 때 휴대전화 본인 인증으로 가능
> * 비밀번호 찾기
>   
>   * 사용자가 비밀번호를 직접 찾을 수 있게 **_-> kt 보안 정책에 괜찮나요?_**

 해당부분은 부가기능이기에 먼저 로그인 프로세스가 가능하게 된 후에 생각하면 좋을 것 같습니다.
그리고 가능하면 ID 기억하기 같은 기능도 추가 할 수 있으면 좋을 것 같네요

> ### 본문
> * 지원페이지 이동
>   
>   * 접수 진행 중인 강좌들을 각각 이미지로 만들어서, 해당 이미지를 클릭하면 지원페이지로 바로 이동하는 기능
>   * 지원페이지로 이동 후, 지원하는 강좌가 자동으로 선택 <br>

본문에서 강좌 진행중인 이미지를  재직자 / 교육자 기준으로 나누어 아래와 같은 캐러셀 형태로 구현하면 어떨까요? <br>
![carousel](https://user-images.githubusercontent.com/62874963/108969975-2ff2ac80-76c5-11eb-888d-35a9b0a20da7.gif)

**Comment by EunjinKwon** [comment]
## 카테고리
###### 카테고리명은 미정

### 회사소개
+ 기능보다는 설명과 UI 가 중요해 보임
***

### 컨소시엄소개
+ 기능보다는 설명과 UI 가 중요해 보임
+ 협력사 소개 추가
  + 이름/주소

***
### 과정안내
+ 재직자 교육 소개
  + 재직자와 채용예정자 카테고리 분리
  + 기대효과 등 이미지로 제작
+ 채용예정자 교육 소개
  + 수강내용, 기간 등은 일정하므로 이미지로 제작
+ 교육일정/교육과정 안내
  + 교육일정과 교육과정의 내용이 많이 겹치므로 하나로 합치기
  + **_밑 주소 참고해서 제작하는 건 어떨까요_**
http://kgacademy.kr/jobtraining/main.php
    + 이미지에 커서를 올리면 과정상세가 뜨고, 과정상세 클릭 시 기존의 교육과정 글과 연결
+ 지원하기
  + 증명사진 첨부, 크기 편집
  + 주소 찾기
  + 학교 검색
    + 입학 년/월, 졸업 년/월 선택
  + 자격증 검색
  + 임시 저장


***
### 교육장안내
+ 위치 안내
  + 지도api 연동
+ 시설 안내
  + 밑 주소 참고하여 사진 편집, 강의실 소개글들을 추가
https://www.ssafy.com/ksp/servlet/swp.content.controller.SwpContentServlet


***
### 고객지원
+ 공지사항
+ FAQ
+ 1:1문의
  + 로그인을 해야 접속 가능
  + 사용자는 이름/이메일/문의유형/제목/문의내용 을 작성
  + 1:1문의 게시판에는 제목/등록일/진행상태 표시
  + 답변이 홈페이지에도 등록되고, 메일로도 전송
  + _**답변을 마이페이지에서 보게 할 건지, 1:1문의 게시판에서 보게 할 건지 정해야 할 것 같아요**_
+ 자료실
  + 사용하지 않으므로 구현하지 않는 것이 좋을 것 같습니다.
+ 이벤트
  + 자료실과 마찬가지로 사용하지 않으므로 구현하지 않는 것이 좋을 것 같습니다.
***

###### 추가하거나 수정할 기능, 내용들 코멘트 부탁드립니다

**Comment by rnin9** [comment]
@EunjinKwon 

>### 회사소개
>
>* 기능보다는 설명과 UI 가 중요해 보임
>### 컨소시엄소개
>* 기능보다는 설명과 UI 가 중요해 보임
>* 협력사 소개 추가
>* 이름/주소

회사소개와 컨소시엄소개를 나눌필요없이 붙이면 좋을거 같은데 어떻게 생각하시나요? 회사 KT인걸 알 것이고 안에 서브메뉴들이 있는것도 아닌데 나눌필요가 있을지 고민입니다.

>### 과정안내
>
> * 지원하기
>   * 증명사진 첨부, 크기 편집
>   * 주소 찾기
>   * 학교 검색
>     * 입학 년/월, 졸업 년/월 선택
>   * 자격증 검색
>   * 임시 저장

지원하기  process를 생각해봐야할것 같습니다. 지원하기에 대한 submenu를 만들지, 아니면 **'자세히'** 에 첨부해주신 이미지처럼 나와있는 이미지를 클릭하면 이미 지원한경우, 알림으로 주고 작성된 지원서를 보여주고, 아닌경우 지원서 작성페이지로 이동하는 화면을 주는건 어떨까요?

**Comment by yeohu0910** [comment]
>   
>   * 수강 중/수강 완료한 강의, 수강 후기 작성
>   * 강의 평가는 종이로 해야 한다고 하셨어서 구현하지 않아도 될 듯
> 
--- 
수강 후기는 수강 완료한 강의에 한해서 작동하게끔 설정하거나, 수강후기를 작성하면 수강 완료 처리되도록 하는 것도 좋을 것 같습니다.


> ### 교육장안내
> * 시설 안내
>   
> 
기존 홈페이지 기준으로, R, G, B로 나누어서 강의실을 분류합니다.
처음 교육을 지원하는 사람이, 본인이 어느 강의실에서 교육 받는지 확인할 수 있도록, 강의실을 나눠서 보여주면 좋을 것 같습니다. 

> ### 고객지원
> * 공지사항
> * FAQ
> * 1:1문의
>   
>   * 로그인을 해야 접속 가능
>   * 사용자는 이름/이메일/문의유형/제목/문의내용 을 작성
>   * 1:1문의 게시판에는 제목/등록일/진행상태 표시, 제목 클릭 시 답변 확인 가능
>   * 답변이 홈페이지에도 등록되고, 메일로도 전송

1:1문의는 로그인 하지 않아도 작성할 수 있게 하고, 비밀번호를 만들어서 본인만 확인할 수 있게 하는 건 어떨까요?
아래 사진은 구글에서 긁어온 것인데, 
**비밀글 작성** 이라는 체크박스를 하나 만들어서, 체크한 사람은 비밀번호를 작성하도록 하고, 
질문할 때는 분류에서 큰 카테고리를 설정하도록 하면 좋을 것 같습니다. (기존 FAQ의 큰 틀)
답변 메일 전송도, 답변 등록 sms전송처럼 **답변 완료시 메일 전송** 같은 체크박스를 선택하게 하는 것도 좋을 것 같습니다.
![5c08f0e629f6402cd641d0effbede7af_1547863509_9456](https://user-images.githubusercontent.com/79436054/109107336-de095f80-7774-11eb-952c-2564647c3da7.png)

**Comment by clair-deLune** [comment]
**회사 소개**
회사 소개의 경우 'kt ds 교육시설'의 명칭이 'kt ds university' 이고 자사의 직원 교육 및 국가 기관과 함께 컨소시엄을 운영하고 있다는 식으로 조금 더 디테일한 설명이 들어가는 방향이 조금 더 좋지 않을까 생각합니다.

**지원하기**
메인 화면에서 과정을 클릭하면 상세 안내 페이지로 이동하고, 상세 안내 페이지 상단과 하단에 지원하기 버튼을 배치하여 구조를 단순화 하는것이 직관적이지 않을까 생각합니다.
또한 이력서 작성페이지에 개인정보 보호 30분 로그아웃을 위한 시간 카운트 다운과 임시 저장시간 표시, 글자수 체크, 지원 후 지원완료 메일 발송 등의 부가 기능을 추가하면 좋으리라 생각합니다.  또한 작성 완료후 이력서 양식에 맞춰 미리 보기화면을 제공하고 최종지원하기 버튼을 넣어 지원자가 다시한번 확인 할 수 있는 페이지를 제공하면 좋을 것 같습니다.

**교육장 안내**
[https://www.ktds.com/company/about_location.jsp](url)
kt ds 자체의 위치 안내가 담긴 링크입니다. 이와 같은 양식으로 위치를 안내하고 조금 더 디테일하게 엘리베이터가 아닌 계단으로 출입하는 방식 등을 담은 디테일한 교육장 안내를 구성해보는 것은 어떨까요?

또한 관리자가 채용예정자 과정의 수강생이 확정 된후 관리페이지에서 승인하면 나타나는 기수별 게시판을 만들어 보는 것이 어떨까 싶은데 이에 관한 의견 부탁드립니다.

**Comment by EunjinKwon** [comment]
> @rnin9 
> 
> > ### 회사소개
> > 
> > * 기능보다는 설명과 UI 가 중요해 보임
> > 
> > ### 컨소시엄소개
> > 
> > * 기능보다는 설명과 UI 가 중요해 보임
> > * 협력사 소개 추가
> > * 이름/주소
> 
> * [x]   회사소개와 컨소시엄소개를 나눌필요없이 붙이면 좋을거 같은데 어떻게 생각하시나요? 회사 KT인걸 알 것이고 안에 서브메뉴들이 있는것도 아닌데 나눌필요가 있을지 고민입니다.
**->  매우 매우 동의합니다! 저도 그렇게 하고 싶었어요** 


> 
> > ### 과정안내
> > 
> > * 지원하기
> >   
> >   * 증명사진 첨부, 크기 편집
> >   * 주소 찾기
> >   * 학교 검색
> >     
> >     * 입학 년/월, 졸업 년/월 선택
> >   * 자격증 검색
> >   * 임시 저장
> 
> * [x]   지원하기  process를 생각해봐야할것 같습니다. 지원하기에 대한 submenu를 만들지, 아니면 **'자세히'** 에 첨부해주신 이미지처럼 나와있는 이미지를 클릭하면 이미 지원한경우, 알림으로 주고 작성된 지원서를 보여주고, 아닌경우 지원서 작성페이지로 이동하는 화면을 주는건 어떨까요?
**->교육과정안내 페이지에 있는 이미지(**아래 있는 '사진' 클릭**)를 클릭하면 학습개요/목표/대상/내용을 알려주는 과정상세 페이지로 이동하고, 그 과정상세 페이지에 지원하기 버튼을 추가하는 것이 좋을 것 같습니다.
페이지 진행은 -> http://hrd.kgitbank.co/jobtraining/main.php 을 참고,
과정상세페이지는 -> https://edu.ktdsuniversity.com/lecture/lecture_view.action 을 참고해주세요.**
<details>
    <summary>사진</summary>

![subject](https://user-images.githubusercontent.com/77440874/109107393-fa0d0100-7774-11eb-8c80-c502f9eff460.PNG)

</details>

**그리고 지원하기는 과정안내 메뉴와 분리 해 새로운 메뉴로 만드는 것이 좋을 것 같네요! 그리고 로그인한 사용자만 접근 가능하게요** 

![apply](https://user-images.githubusercontent.com/77440874/109107326-db0e6f00-7774-11eb-98f4-1d470228b1e9.PNG)

**지원하기 페이지는**

+ 게시판형식으로 만들어서 지원한 과정 이름, 날짜, 현황 등을 보여주고 **_(여러 과정을 신청할 수도 있으니 지원서도 여러 번 작성할 수 있잖아요? 그러니까 게시판 형식으로 먼저 뜨게 만드는 건 어때요?)_**
+ 지원하기 버튼을 따로 만들어서 클릭하면 작성페이지로 넘어가게

**하면 될것같습니다
이미 지원을 했어도, 하지않았어도 지원하기를 클릭하면 지원하기 페이지로 이동하게 하는 게 덜 복잡할 것 같아요**

**아!!! 그리고 지원하기를 클릭했을 때 지원자격, 지원내용(20만원 ㅎ), 선발진행과정 등을 알려주는 페이지가 먼저 뜨는 것도 필요하겠어요!**
#### 정리하자면 홈에서 지원하기 메뉴 클릭(또는 과정상세페이지에서 지원하기 버튼 클릭)->자격요건 등을 알려주는 페이지로 연결되고->그 페이지에 있는 지원하기 버튼을 클릭하면 개인의 지원게시판 페이지로 연결-> 그 페이지에 있는 지원하기 버튼을 클릭하면 진짜 지원서 작성 페이지로 연결..! 입니다

**Comment by EunjinKwon** [comment]
@clair-deLune 
> **회사 소개**
> 회사 소개의 경우 'kt ds 교육시설'의 명칭이 'kt ds university' 이고 자사의 직원 교육 및 국가 기관과 함께 컨소시엄을 운영하고 있다는 식으로 조금 더 디테일한 설명이 들어가는 방향이 조금 더 좋지 않을까 생각합니다.
> 
> **지원하기**
> 메인 화면에서 과정을 클릭하면 상세 안내 페이지로 이동하고, 상세 안내 페이지 상단과 하단에 지원하기 버튼을 배치하여 구조를 단순화 하는것이 직관적이지 않을까 생각합니다.
> 또한 이력서 작성페이지에 개인정보 보호 30분 로그아웃을 위한 시간 카운트 다운과 임시 저장시간 표시, 글자수 체크, 지원 후 지원완료 메일 발송 등의 부가 기능을 추가하면 좋으리라 생각합니다. 또한 작성 완료후 이력서 양식에 맞춰 미리 보기화면을 제공하고 최종지원하기 버튼을 넣어 지원자가 다시한번 확인 할 수 있는 페이지를 제공하면 좋을 것 같습니다.
>> **작성해주신 기능을 정리해봤어요**
>>+ **자동 로그아웃**
>>+ **글자수 체크**
>>+ **지원완료 메일 발송 -> 지원서 수정 기능은 없는 게 낫겠네요!**
>>+ **미리보기**
>>
>>**모두 좋은 기능 같아요!!!**
> 
> **교육장 안내**
> [https://www.ktds.com/company/about_location.jsp](url)
> kt ds 자체의 위치 안내가 담긴 링크입니다. 이와 같은 양식으로 위치를 안내하고 조금 더 디테일하게 엘리베이터가 아닌 계단으로 출입하는 방식 등을 담은 디테일한 교육장 안내를 구성해보는 것은 어떨까요?

>> **알려주신 사이트 참고해서 계단 출입 방식도 추가하면 되겠네요!**
> 
> 또한 관리자가 채용예정자 과정의 수강생이 확정 된후 관리페이지에서 승인하면 나타나는 기수별 게시판을 만들어 보는 것이 어떨까 싶은데 이에 관한 의견 부탁드립니다.

**Comment by rnin9** [comment]
작성해주신 사항들 다 읽어 보았고, 현재까지 생각한 사항들을 정리해 보았습니다. 

## 현 기능정리
|   컨소시엄   	|    과정관리    	|  지원하기  	| 교육장안내 	| 고객지원 	|
|:------------:	|:--------------:	|:----------:	|:----------:	|:--------:	|
| 운영기관소개 	|   재직자과정   	| 이력서관리 	|  오시는길  	| 공지사항 	|
|              	| 채용예정자과정 	| 지원서관리 	| 교육장안내 	|    FAQ   	|
|              	|                	|            	|            	|  1:1문의 	|

<details>
    <summary>세부사항</summary>


## 컨소시엄
* 운영기관소개
  * 운영기관에 대한 정보를 보여줍니다 ex) KT DS or 공단 등등 
## 과정관리
* 재직자과정
  * 재직자 과정에 대한 정보를 보여줍니다 ex) 강의 목록, @EunjinKwon 이  **'자세히'** 에서 보여준 방식으로 이동하면 좋을것 같습니다.
 * 채용예정자과정
   * 재직자 과정과 동일.
## 지원하기 
**_->해당부분을 아래와 같이 바꿔보았습니다._**
 * 이력서관리
   * 자기소개서에 대한 부분을 작성하는 메뉴
 * 지원서관리
   * 지원하는 회사에 대한 부분을 작성하는 메뉴  

추가 사항)
자동 로그아웃
글자수 체크
지원완료 메일 발송 
미리보기   
 
## 교육장안내  
* 오시는길
  * 지도 API와 올라오는 방식에 대한 부분 @clair-deLune  
* 교육장안내 
  * 교육장 내부 R, G, B 형식 @yeohu0910  
## 고객지원 
* 공지사항
  * 공지사항에 대한 부분
*  FAQ 
  * FAQ에대한 부분
*  1:1문의
  * 1:1 문의시 로그인/ 비로그인 방식 중 택1 
  @yeohu0910 의 비밀글 작성 방식 고려 
</details>

이외에도 


- [x]  로그인,회원가입 
* 아이디, 비밀번호 찾기
   * 전화인증
 * SNS 간편 가입
   * 회원가입시 실명인증 (휴대폰)
- [x]  마이페이지
* 지원 현황
  * 지원서 관리 및 제출 현황, 결과 확인
 * 수강 강의 확인
   * 수강 중/수강 완료한 강의, 수강 후기 작성
 * 협력사 채용
   * 로그인 된 회원의 채용을 원하는 협력사들 정보 <br>**_=> 해당기능을 로그인 이후 알림이 오도록 만들거나, Mypage에서 알려준다면 좀 더 완성도 있는 페이지가 될 수 있을것 같습니다._**  
 ___
위와 같은 기능이 필요하다고 작성해 주셨습니다.

여기서 더 고칠 사항을 논의 해 주시고, 위에 comment들 중 놓친 사항이 있으시면 말씀해 주시면 수정하겠습니다.

**Comment by ksh0310** [comment]
## 지원하기 
 * 이력서관리
   * 자기소개서에 대한 부분을 작성하는 메뉴
 * 지원서관리
   * 지원하는 회사에 대한 부분을 작성하는 메뉴 

**----> 이력서관리와 지원서관리 기능의 차이를 잘 모르겠습니다..**

![image](https://user-images.githubusercontent.com/79489832/109140385-e0cd7a00-779f-11eb-85b9-8597f0d76881.png)

**그리고 그림과 같이 지원기간 내에는 지원서를 냈어도 수정할 수 있도록 하고 지원기간이 지나면 수정할 수 없게 하면 좋을 것 같습니다. 이미 제출한 지원서도 볼 수 있게 하고 취소하고 싶은 경우가 있을 수도 있으니 반환 기능을 넣어도 좋을 것 같습니다.** 


![image](https://user-images.githubusercontent.com/79489832/109140920-7537dc80-77a0-11eb-82b3-bdaf9161a563.png)
https://github.com/rnin9/KT-ds-University-17th-web-application-project/issues/1#issuecomment-785630070 **위에서 말한 것처럼 그림과 같이 Life와 Apply를 따로 만드는 부분은 좋을 것 같습니다.** **Life 부분에 후기, 이전 기수들 소개가 들어가면 좋을 것 같습니다.**

**그리고 과장님께서 자신 있어서 취업률, 취업한 회사들을 넣지 않았다고 하셨지만 채용예정자 과정을 지원할 때 사람들이 가장 많이 보는 부분 중 하나라고 생각해서 넣는 게 좋다고 생각합니다.**

## 고객지원
- [x]  마이페이지
**마이페이지에 수료증 출력 기능이 필요할 거 같습니다.**

**Comment by rnin9** [comment]
@ksh0310 https://github.com/rnin9/KT-ds-University-17th-web-application-project/issues/1#issuecomment-785804187 에관한 내용입니다.
<br>

> **Q. ----> 이력서관리와 지원서관리 기능의 차이를 잘 모르겠습니다..**
>> 이력서 관리라고 적어 놓은 부분은 KT ds에서 수강신청시 제출하는 형식에 맞춰 작성한 페이지라고 볼 수 있습니다. 저희가 제출했었던 신청서 형식처럼 정해진 형식을 따라 웹에서 직접 작성할 수 있도록 구성하려 했습니다. 
>> 
>> 지원서 관리는 협약사의 채용정보 같은 부분을 넣고자 했습니다. 협력사마다 다른 형식이 존재할 수 있으므로, 게시판 형식으로 신청서 파일을 협력사마다 업로드 하고, 파일을 지원자가 다운받는 형식을 취하고자 두 메뉴를 나누어야 겠다고 생각한 것입니다.  생각해보니 메인메뉴의 이름 때문에 헷깔릴 수 도 있을거 같습니다. 좀 더 와닿는 메뉴이름을 논의해야할 것 같네요.

<br>

> **그리고 그림과 같이 지원기간 내에는 지원서를 냈어도 수정할 수 있도록 하고 지원기간이 지나면 수정할 수 없게 하면 좋을 것 같습니다. 이미 제출한 지원서도 볼 수 있게 하고 취소하고 싶은 경우가 있을 수도 있으니 반환 기능을 넣어도 좋을 것 같습니다.**
>> 구현이 가능한지는 고민해보아야 하겠지만, 수정, 삭제 부분은 당연히 구현해야 할 부분입니다. 신청 기간이 지나면 버튼이 사라지게 만들면 될것 같네요.
 
<br>

> [#1 (comment)](https://github.com/rnin9/KT-ds-University-17th-web-application-project/issues/1#issuecomment-785630070) **위에서 말한 것처럼 그림과 같이 Life와 Apply를 따로 만드는 부분은 좋을 것 같습니다.** **Life 부분에 후기, 이전 기수들 소개가 들어가면 좋을 것 같습니다.**
>> 고민해야할 부분일 것 같습니다. 정리한 부분인 교육장 안내라는 메뉴의 이름을 바꾸어서 사진처럼 Life 같은 형식으로 만들고, 후기를 하위 메뉴로넣는것도 괜찮을것 같네요. 

<br>

> **그리고 과장님께서 자신 있어서 취업률, 취업한 회사들을 넣지 않았다고 하셨지만 채용예정자 과정을 지원할 때 사람들이 가
> 장 많이 보는 부분 중 하나라고 생각해서 넣는 게 좋다고 생각합니다.**
>> 데이터 시각화 부분에서 통계자료로 사용 할 수 있는 부분 같습니다. 좋아보이네요.

<br>

>   **마이페이지에 수료증 출력 기능이 필요할 거 같습니다.**
>> 넣고싶은 부분입니다. 출력이 가능하면 좋을것 같습니다.

**Comment by rnin9** [comment]
## 기본기능
* 회원가입 / 로그인
*  권한 별 정보 확인
* 과정관리 (재직자 / 채용예정자)
* 수강관리 ( 사용자 수강정보 관리 )
* 지원서 관리 ( 제출서류 관리 ) 
* 공지사항 , 1:1 문의, 수강후기

## 부가기능
* 수료증 출력
* 회원가입시 실명인증
* SNS간편가입
* 취업률, 취업가능 기업 확인

<details>
    <summary>기능소개</summary>

|   컨소시엄   	|    과정소개   	|  지원하기  	| 교육장안내 	| 고객지원 	|
|:------------:	|:--------------:	|:----------:	|:----------:	|:--------:	|
| 운영기관소개 	|   재직자과정   	| 이력서관리 	|  오시는길  	| 공지사항 	|
|              	| 채용예정자과정 	| 지원서관리 	| 교육장안내 	|       	FAQ|  
|              	|       수강후기         	|            	|            	|  1:1문의 	|

<details>
    <summary>세부사항</summary>


## 컨소시엄
* 운영기관소개
  * 운영기관에 대한 정보를 보여줍니다 ex) KT, KT ds or 공단 등등 
## 과정소개
* 재직자과정
  * 재직자 과정에 대한 정보를 보여줍니다 ex)  https://github.com/rnin9/KT-ds-University-17th-web-application-project/issues/1#issuecomment-785630070 [과정안내-지원하기] 에서 보여준 방식으로 이동하면 좋을것 같습니다.
 * 채용예정자과정
   * 재직자 과정과 동일.
 * 수강후기
   * 수료학생의 수강후기.

## 지원하기 
 * 이력서관리
   * 자기소개서에 대한 부분을 작성하는 메뉴
 * 지원서관리
   * 지원하는 회사에 대한 부분을 작성하는 메뉴  

추가 사항)
자동 로그아웃
글자수 체크
지원완료 메일 발송 
미리보기   
 
## 교육장안내  
* 오시는길
  * 지도 API와 올라오는 방식에 대한 부분 @clair-deLune  https://github.com/rnin9/KT-ds-University-17th-web-application-project/issues/1#issuecomment-785623106
* 교육장안내 
  * 교육장 내부 R, G, B 형식 @yeohu0910 https://github.com/rnin9/KT-ds-University-17th-web-application-project/issues/1#issuecomment-785622642
## 고객지원 
* 공지사항
  * 공지사항에 대한 부분
*  FAQ 
   * FAQ에대한 부분
 *  1:1문의
    * 1:1 문의시 로그인/ 비로그인 방식 중 택1 
  @yeohu0910 https://github.com/rnin9/KT-ds-University-17th-web-application-project/issues/1#issuecomment-785622642 의 비밀글 작성 방식 고려 
</details>

- [x] 이외


* 로그인,회원가입 
   * 아이디, 비밀번호 찾기
    * 전화인증
 * SNS 간편 가입
   * 회원가입시 실명인증 (휴대폰)
* 마이페이지
  * 지원 현황
  * 지원서 관리 및 제출 현황, 결과 확인
 * 수강 강의 확인
   * 수강 중/수강 완료한 강의, 수강 후기 작성
 * 협력사 채용
 *  수료증 출력
