### ISSUE TITLE
Resume (이력서)

### ISSUE THREAD

**Issue by yeohu0910** [rnin9/KT-ds-University-17th-web-application-project#13]
이력서에 대한 테이블입니다. 관련된 Attribute, Constraint에 대해서 논의하세요

**Comment by yeohu0910** [comment]
> > ```
> > CREATE TABLE RESUME (
> >	  resumeID varchar2(30) not null,			
> >   resumeUser varchar2(30) not null,			
> >   resumeEdu varchar2(30) not null,			                // 학력
> >   resumeCareer varchar2(50) not null,		        	        // 경력
> >   resumeCareerText varchar2(50) not null,	         	        // 경력 사항
> >   resumeLicense varchar2(30) not null,		                        // 자격증
> >   resumePic char(1) default 'N',			                // 사진 첨부
> >   CONSTRAINT PK_RESUME PRIMARY KEY (resumeID), 			        // PK 설정
> >   CONSTRAINT FK_USER FOREIGN KEY(resumeUser)
> >   REFERENCES USER(userID),				                // FK 설정
> >   CONSTRAINT CHECK_PIC CHECK(resumePic IN ('Y', 'N')),		        // 사진 첨부 여부(Y, N)
> >  );
> > ```
> > 
> > 
> > 
> > 1. 각 이력서 마다 고유의 번호를 가져야 하기 때문에, resumeID를 PK로 지정하였습니다.
> > 2. 사진 첨부 여부를 @rnin9 님이 이력서 제출 여부를 확인하신 것처럼 Y와 N으로 구분하게 했습니다.
> > 3. 추가가 안된 부분이 이력서 내용 부분인데, 각 회사마다 이력서 양식 여부가 다르기 때문에 이력서의 첫장은 홈페이지에서 작성하도록 하고, 뒷장은 파일 첨부하는 형식으로 확인해도 좋을 것 같은데, 다른 의견 부탁드립니다. 첨부하는 형식이 아니라면, resumeContext1부터 5까지 각각 varchar2(1000)으로 설정해서 추가하겠습니다.
> > 4. @rnin9 님의 USER 테이블 참조하여 FK 설정했습니다.
> > 5. 더 추가할 속성이나 제약사항등이 있으면 코멘트 부탁드립니다. 감사합니다.

**Comment by rnin9** [comment]
>>  **2. 사진 첨부 여부를 @rnin9 님이 이력서 제출 여부를 확인하신 것처럼 Y와 N으로 구분하게 했습니다.**
>* 해당부분은 사진이름을 저장할 수 있도록 해야할 것 같습니다. 보통 사진을 업로드 하는 경우 파일 자체를 DB에서 가지고있기 보다는, 파일이름을 저장해 놓고 서버에 올라간 사진 파일의 이름을 따라 사진을 보여주는 경우가 많습니다. Y와N으로 해 놓는다면 서버의 어떤사진이 자신이 업로드한 사진인지 확인하기 힘들겁니다. 넉넉하게 varchar2(80) 정도가 어떨까 싶네요. 이름이 굉장히 긴 경우도 많아서...

>> **3. 추가가 안된 부분이 이력서 내용 부분인데, 각 회사마다 이력서 양식 여부가 다르기 때문에 이력서의 첫장은 홈페이지에서 작성하도록 하고, 뒷장은 파일 첨부하는 형식으로 확인해도 좋을 것 같은데, 다른 의견 부탁드립니다. 첨부하는 형식이 아니라면, resumeContext1부터 5까지 각각 varchar2(1000)으로 설정해서 추가하겠습니다.**
>* @EunjinKwon 님이 확인한 결과 협력사마다 제출하는 이력서 내용은 모두 동일하다고 합니다. 저희가 제출한 이력서형식에 맞춰 작성을 하면 좋겠고, Resume는 테이블 분할이 필요할 것 같습니다. 자격증을 예시로 들면, 하나만 가지고있는 것이 아니라, 여러가지 자격증을 가지고 있을 수 있기때문에 User의 userID, Resume의 resumeID를 FK로 가지고있는 Resume_certificate 테이블을 만들어서 각 User마다 Resume의 자격증들을 가지고 있는 테이블을 만들고 하는 식으로 해야할 것 같습니다.

**Comment by yeohu0910** [comment]
> > ```sql
> > CREATE TABLE RESUME (
> >   resumeID varchar2(30) not null,			
> >   resumeUser varchar2(30) not null,			
> >   resumePic varchar2(80) not null,			// 사진 첨부
> >   resumeSpecial char(1) default 'N',			// 보훈 여부 기본값 N으로 설정
> >   resumeArmy char(1) default 'Y',			// 군필 여부 기본값 Y로 설정
> >   resumeLicense varchar2(30) not null,		        // 자격증
> >   resumeContext1 varchar2(1000) not null,               // 이력서 1번 항목
> >   resumeContext1 varchar2(1000) not null,               // 이력서 2번 항목
> >   resumeContext1 varchar2(1000) not null,               // 이력서 3번 항목
> >   resumeContext1 varchar2(1000) not null,               // 이력서 4번 항목
> >   resumeContext1 varchar2(1000) not null,               // 이력서 5번 항목
> >   CONSTRAINT PK_RESUME PRIMARY KEY (resumeID),          // PK 설정
> >   CONSTRAINT FK_USER FOREIGN KEY(resumeUser)
> >   REFERENCES USER(userID),		                // FK 설정
> >   CONSTRAINT CHECK_SPECIAL CHECK(resumeSpecial IN('Y', 'N')),
> >                                                         // 보훈 여부 확인
> >   CONSTRAINT CHECK_ARMY CHECK(resumeArmy IN('Y', 'N'))	// 군필 여부 확인
> >  );
> > ```
> > 
> > 
> > 
> > 1.  @rnin9 님이 말씀해주신대로, 저희가 작성할 이력서를 기준해서 작성했습니다.
> >  [★kt ds University 이력서 양식.pdf](https://github.com/rnin9/KT-ds-University-17th-web-application-project/files/6187891/kt.ds.University.pdf)

> > 2.  추가되어야 할 부분으로 자격증, 외국어시험(TOEIC), 프로젝트,  경력, 학력, 교육기관에서의 교육내용 (kt ds등)이 추가되어야 합니다.
> > 3. 하나의 이력서 테이블에 다 담을 수 없어서, <br> 자격증과 외국어 시험을 합친 **RESUME_CERTIFICATE** 테이블과 <br> 경력내용과 교육기관 내용을 합친 **RESUME_CAREER**테이블, <br> 프로젝트 내용을 담은 **RESUME_PROJECT** 테이블로 나누어 작성했습니다.
> > 4. 변경사항은 추가 이슈 작성해서 업데이트 하겠습니다. 확인 부탁드립니다.

**Comment by yeohu0910** [comment]
> > ```sql
> > CREATE TABLE RESUME (
> >   resumeID varchar2(30) not null,			
> >   resumeUser varchar2(30) not null,	
> >   resumeForeign varchar2(30) not null,                  /* 영문명 */
> >   resumeIDnumber varchar2(15) not null,                 /* 주민번호 */		
> >   resumePic varchar2(100) not null,			/* 사진 첨부 */
> >   resumeSpecial char(1) default 'N',			/* 보훈 여부 기본값 N으로 설정 */
> >   resumeArmy char(1) default 'Y',			/* 군필 여부 기본값 Y로 설정 */
> >   resumeSchool varchar2(50) not null,			/* 출신 학교 확인 */
> >   resumeContext1 varchar2(1000) not null,               /* 이력서 1번 항목 */
> >   resumeContext2 varchar2(1000) not null,               /* 이력서 2번 항목 */
> >   resumeContext3 varchar2(1000) not null,               /* 이력서 3번 항목 */
> >   resumeContext4 varchar2(1000) not null,               /* 이력서 4번 항목 */
> >   resumeContext5 varchar2(1000) not null,               /* 이력서 5번 항목 */
> >   CONSTRAINT PK_RESUME PRIMARY KEY (resumeID),          /* PK 설정 */
> >   CONSTRAINT FK_USER FOREIGN KEY(resumeUser)
> >   REFERENCES USER(userID),		                /* FK 설정 */
> >   CONSTRAINT CHECK_SPECIAL CHECK(resumeSpecial IN('Y', 'N')),
> >                                                         /* 보훈 여부 확인 */
> >   CONSTRAINT CHECK_ARMY CHECK(resumeArmy IN('Y', 'N'))	/* 군필 여부 확인 */
> >  );
> > ```
> > 
> > 
> > 
> > 
> >  [★kt ds University 이력서 양식.pdf](https://github.com/rnin9/KT-ds-University-17th-web-application-project/files/6187891/kt.ds.University.pdf)
> > 1. 3월 25일 회의 결과 내용 반영해서, 본 테이블은 협력사에 지원하는 **이력서** 테이블이고, <br> 추가로 kt ds university에 지원하는 **지원서** 테이블 작성하겠습니다.
> > 2. 추가 컬럼 내용으로 **영문명**과 **주민번호**가 추가되었습니다.
> > 3. 추가 문의사항으로,  현재 **학력** 관련해서  **resumeSchool** 컬럼을 통해 출신 학교만 확인하는데, <br> 첨부된 파일을 확인해보시면 **기간, 졸업구분, 성적** 등이 추가로 작성되어야 하는 부분이 있습니다. <br> 소속 학력을 고등학교부터 대학원까지 전부 확인한다고 가정하면 추가 테이블 작성이 필요할 듯 한데 추가 의견 부탁드립니다.
