### ISSUE TITLE
Partner (협력사)

### ISSUE THREAD

**Issue by rlarhkd** [rnin9/KT-ds-University-17th-web-application-project#14]
협력사에 대한 테이블입니다. 관련된 Attribute, Constraint에 대해서 논의하세요

**Comment by rlarhkd** [comment]
> ```
> CREATE TABLE PARTNER(
>   partnerLicenseNum varchar2(30) PRIMARY KEY,          //협력사 사업자번호
>   partnerName varchar2(30) not null,                   //협력사 명 
>   partnerInformation varchar2(50) not null,            //간단한 회사 정보 ?
>   partnerAddres varcher2(50) not null,                 //협력사 주소 
>   partnerPhoneNumber varchar2(13)  not null,           //협력사 전화번호
>   partnerEmail varchar2(50) not null,                  //협력사 이메일
>  );
>```
>1. 사업자 번호는 기업별로 고유한 번호이기 때문에 Partner테이블의 Primary key로 지정하였습니다.
>2. 간단한 회사의 정보를 속성으로 나타내었는데 꼭 있어야되는지 잘 모르겠습니다. 코멘트 부탁드립니다.
>3. 협력사별소속된 회원 정보(회원, 수강내역...등)을 조회하기 위해 Partner테이블과 user 테이블을 join하여 자주 사용될것 같습니다. **협력사 명**을 user테이블에서 Foriegn key로 지정하여 join을 하면 좋을것 같습니다.
>4. 더 추가할 속성이나 제약사항등이 있으면 코멘트 부탁드립니다.

**Comment by rnin9** [comment]
> > 2. 간단한 회사의 정보를 속성으로 나타내었는데 꼭 있어야되는지 잘 모르겠습니다. 코멘트 부탁드립니다.
> * 회사 정보는 필요할 것 같습니다. 지원시 참조할 수 있는 정보들 ex) 산업 분야, 개발 분야를 나타내는 Column으로 사용하면 좋을 것 같습니다. 
> > 3. 협력사별소속된 회원 정보(회원, 수강내역...등)을 조회하기 위해 Partner테이블과 user 테이블을 join하여 자주 사용될것 같습니다. **협력사 명**을 user테이블에서 Foriegn key로 지정하여 join을 하면 좋을것 같습니다.
> * 제대로 이해가 안가서 그런데 지원한 사람들의 수강 정보를 확인한다는 의미일까요?
> > 4. 더 추가할 속성이나 제약사항등이 있으면 코멘트 부탁드립니다.
> >또한 회사 대표 명, 인원 규모, URL, 모집날짜를 표시해 줄 수 있는 Attribute또한 필요할 것 같습니다.


추가해 봤습니다.

 ```
CREATE TABLE PARTNER(
partnerLicenseNum varchar2(30) PRIMARY KEY,          //협력사 사업자번호
partnerName varchar2(30) not null,                   //협력사 명 
partnerInformation varchar2(50) not null,            //간단한 회사 정보 ?
partnerAddress varcher2(50) not null,                 //협력사 주소 
partnerPhoneNumber varchar2(13)  not null,           //협력사 전화번호
partnerEmail varchar2(50) not null,                  //협력사 이메일
partnerCEO varchar2(20) not null,                   // 협력사 대표명
partnerHeadCount number(5),                          // 인원 규모
partnerApplyDate date,                                     //지원 가능 날짜
partnerURL varchar2(40) not null                      // 회사 홈페이지
);
```

**Comment by rlarhkd** [comment]
>*  회의에서 얘기했던 **지원 가능 날짜** -> **지원 시작 날짜, 지원 마감 날짜**로 나누었습니다.
> 
> ```sql
> CREATE TABLE PARTNER(
>   partnerLicenseNum varchar2(30) PRIMARY KEY,          /*협력사 사업자번호*/
>   partnerName varchar2(30) not null,                   /*협력사 명*/
>   partnerInformation varchar2(50) not null,            /*간단한 회사 정보*/ 
>   partnerAddress varchar2(50) not null,                /*협력사 주소*/ 
>   partnerPhoneNumber varchar2(13)  not null,           /*협력사 전화번호*/
>   partnerEmail varchar2(50) not null,                  /*협력사 이메일*/
>   partnerCEO varchar2(20) not null,                    /*협력사 대표명*/
>   partnerHeadCount number(5),                          /*인원 규모*/
>   partnerApplyStartDate date,                          /*지원 시작 날짜*/
>   partnerApplyFinishDate date,                         /*지원 마감 날짜*/
>   partnerURL varchar2(40) not null                     /*회사 홈페이지*/
> );
> ```

**Comment by rlarhkd** [comment]
>*  25일에 회의에서 얘기했던 **협력사가 아니거나** 혹은 **채용예정자**의 경우에는 LicensNum을 **kt ds university** 를 pk에 들어가게 테이블에 추가하고 나머지 값으로는 null값이 들어갈 수 있게 속성들을 바꿨습니다.
> 
> ```sql
> CREATE TABLE PARTNER(
>   partnerLicenseNum varchar2(30) ,   /*협력사 사업자번호*/
>   partnerName varchar2(30),                   /*협력사 명*/
>   partnerInformation varchar2(50),            /*간단한 회사 정보*/ 
>   partnerAddress varchar2(50),                /*협력사 주소*/ 
>   partnerPhoneNumber varchar2(13),             /*협력사 전화번호*/
>   partnerEmail varchar2(50),                   /*협력사 이메일*/
>   partnerCEO varchar2(20),                     /*협력사 대표명*/
>   partnerHeadCount number(5),                  /*인원 규모*/
>   partnerApplyStartDate date,                  /*지원 시작 날짜*/
>   partnerApplyFinishDate date,                 /*지원 마감 날짜*/
>   partnerURL varchar2(40),                      /*회사 홈페이지*/
>   CONSTRAINT pk_partner PRIMARY KEY (partnerLicensNum)
> );
> ```

**Comment by rlarhkd** [comment]
> > * 26일에 진행된 인터뷰내용을 토대로 테이블을 변경하였습니다.
> > 1. **협약사**, **협력사**, **미협약**인 회사와 **협약 진행중**인 회사로 구분하는 칼럼을 추가했습니다.
> > ```sql
> > CREATE TABLE PARTNER( 
> >   partnerLicenseNum varchar2(30) ,            /*협력사 사업자번호*/
> >   partnerState char(16) not null,             /*협약 상태*/
> >   partnerName varchar2(30),                   /*협력사 명*/
> >   partnerInformation varchar2(50),            /*간단한 회사 정보*/ 
> >   partnerAddress varchar2(50),                /*협력사 주소*/ 
> >   partnerPhoneNumber varchar2(13),            /*협력사 전화번호*/
> >   partnerEmail varchar2(50),                  /*협력사 이메일*/
> >   partnerCEO varchar2(20),                    /*협력사 대표명*/
> >   partnerHeadCount number(5),                 /*인원 규모*/
> >   partnerApplyStartDate date,                 /*지원 시작 날짜*/
> >   partnerApplyFinishDate date,                /*지원 마감 날짜*/
> >   partnerURL varchar2(40),                    /*회사 홈페이지*/
> >   CONSTRAINT pk_partner PRIMARY KEY (partnerLicenseNum),
> >   CONSTRAINT CK_partner CHECK(partnerState IN ('협약사', '협력사', '미협약','협약 진행중'))
> > );
> > ```

**Comment by rlarhkd** [comment]
> > >
> > > 
> > > ```sql
> > > CREATE TABLE PARTNER( 
> > >   partnerLicenseNum varchar2(30),            /*협력사 사업자번호*/
> > >   partnerState char(16) not null,             /*협약 상태*/
> > >   partnerName varchar2(30),                   /*협력사 명*/
> > >   partnerInformation varchar2(100),           /*간단한 회사 정보*/ 
> > >   partnerAddress varchar2(100),               /*협력사 주소*/ 
> > >   partnerPhoneNumber varchar2(13),            /*협력사 전화번호*/
> > >   partnerEmail varchar2(50),                  /*협력사 이메일*/
> > >   partnerCEO varchar2(20),                    /*협력사 대표명*/
> > >   partnerHeadCount number(5),                 /*인원 규모*/
> > >   partnerApplyStartDate date,                 /*지원 시작 날짜*/
> > >   partnerApplyFinishDate date,                /*지원 마감 날짜*/
> > >   partnerURL varchar2(40),                    /*회사 홈페이지*/
> > >   partnerRegisterDate date default sysdate,        /*회사 등록 날짜 */
> > >   CONSTRAINT pk_partner PRIMARY KEY (partnerLicenseNum),
> > >   CONSTRAINT CK_partner CHECK(partnerState IN ('협약사', '협력사', '미협약','협약 진행중'))
> > > );
> > > ```
> > 1. 협력사 혹은 협약사의 등록 날짜를 추가하였습니다.

**Comment by rlarhkd** [comment]
> > > > ```sql
> > > > CREATE TABLE PARTNER( 
> > > >   partnerLicenseNum varchar2(30),            /*협력사 사업자번호*/
> > > >   partnerState char(16) not null,             /*협약 상태*/
> > > >   partnerName varchar2(30),                   /*협력사 명*/
> > > >   partnerInformation varchar2(100),           /*간단한 회사 정보*/ 
> > > >   partnerAddress varchar2(100),               /*협력사 주소*/ 
> > > >   partnerPhoneNumber varchar2(13),            /*협력사 전화번호*/
> > > >   partnerEmail varchar2(50),                  /*협력사 이메일*/
> > > >   partnerCEO varchar2(20),                    /*협력사 대표명*/
> > > >   partnerHeadCount number(5),                 /*인원 규모*/
> > > >   partnerApplyYN  char(1),                    /*지원 가능 여부*/
> > > >   partnerURL varchar2(40),                    /*협력사 홈페이지*/
> > > >   partnerRegisterDate date default sysdate,        /*협력사 등록 날짜 */
> > > >   CONSTRAINT pk_partner PRIMARY KEY (partnerLicenseNum),
> > > >   CONSTRAINT CK_partner CHECK(partnerState IN ('협약사', '협력사', '미협약', '협약 진행중'))
> > > >   CONSTRAINT YN_partner CHECK(partnerApplyYN IN ('Y,'N'))
> > > > );
> > > > ```
> > > 
> > > 
> > > 
> > > 1. 지원 시작,마감 날짜를 지우고 지원 가능 여부를 **partnerApplyYN** 컬럼을 추가하여 admin(전체) Y로 변경하였을 경우에만 지원이 가능하게 설정하였습니다.

**Comment by rlarhkd** [comment]
> > > > > ```sql
> > > > > CREATE TABLE PARTNER( 
> > > > >   partnerLicenseNum varchar2(30),            /*협력사 사업자번호*/
> > > > >   partnerState char(16) not null,             /*협약 상태*/
> > > > >   partnerName varchar2(30),                   /*협력사 명*/
> > > > >   partnerInformation varchar2(100),           /*간단한 회사 정보*/ 
> > > > >   partnerAddress varchar2(100),               /*협력사 주소*/ 
> > > > >   partnerPhoneNumber varchar2(13),            /*협력사 전화번호*/
> > > > >   partnerEmail varchar2(50),                  /*협력사 이메일*/
> > > > >   partnerCEO varchar2(20),                    /*협력사 대표명*/
> > > > >   partnerHeadCount number(5),                 /*인원 규모*/
> > > > >   partnerApplyYN  char(1) default 'N',                    /*지원 가능 여부*/
> > > > >   partnerApplyFinishDate date,       /*모집 마감 날짜 */
> > > > >   partnerURL varchar2(40),                    /*협력사 홈페이지*/
> > > > >   partnerRegisterDate date default sysdate,        /*협력사 등록 날짜 */
> > > > >   CONSTRAINT pk_partner PRIMARY KEY (partnerLicenseNum),
> > > > >   CONSTRAINT CK_partner CHECK(partnerState IN ('협약사', '협력사', '미협약', '협약 진행중'))
> > > > >   CONSTRAINT YN_partner CHECK(partnerApplyYN IN ('Y,'N'))
> > > > > );
> > > > > ```
> > > > 
> > > > 
> > > > 
> > > > 1. **partnerApplyFinishDate**모집 마감날짜를 다시 추가하였습니다.
