### ISSUE TITLE
Survey (설문조사)

### ISSUE THREAD

**Issue by Parkmsms** [rnin9/KT-ds-University-17th-web-application-project#15]
설문조사에 대한 테이블입니다. 관련된 Attribute, Constraint에 대해서 논의하세요.

**Comment by Parkmsms** [comment]
설문 조사에 대한 항목이 정확히 어떤 건지 잘 몰라가지고 .. 두가지경우로 생각해봤는데
설문조사 내용을 체크박스 형식으로 데이터로 직접 받고 등록 하는건가요 ?!  -**-1**
단순히 아니면 수기로 입력한 설문조사를 DB로 저장하는 건가요? **--2**



**--1 일 경우**
설문조사 내용을 다양한 형식 데이터로 직접 받고 등록 한다면
■SURVEY = 설문 제목, (게시판)
CREATE TABLE SURVEY_QUESTION(
QUESTION_ID NUMBER(30) PRIMARY KEY, //고유번호 (AUTO INCREMENT) <-- 인덱스 생성후 적용 
TITLE VARCHAR2(30) NOT NULL,
DATETIME DATE DEFAULT SYSDATE,
);


■QUESTION_SURVEY = 설문 각각의 질문
CREATE TABLE QUESTION(
QUESTION NUMBER(30) PRIMARY KEY, //(AUTO INCREMENT)
QUESTION_ID NUMBER(30),  (AUTO INCREMENT),
QUESTION VARCHAR2(30) NOT NULL, //질문 내용
CONSTRAINT FK_QUESTION FOREIGN KEY (QUESTION_ID)	
    REFERENCES SURVEY(QUESTION_ID)
);

■QUESTION_OPTION = 각각의 질문에 대한 옵션
CREATE TABLE QUESTION_OPTION(
OPTION_ID NUMBER(30) PRIMARY KEY, //(AUTO INCREMENT)
QUESTION NUMBER(30),
OPTION_KIND  NUMBER(20), //질문의 형식
OPTION_TEXT VARCHAR2(30),  //질문의 텍스트
CONSTRAINT FK_QUESTION_OPTION FOREIGN KEY(QUESTION)
     REFERENCES QUESTION_SURVEY(QUESTION)
);

■QUESTION_ANSWER = 설문 각각의 질문답변
CREATE TABLE QUESTION_ANSWER(
ANSWER_ID NUMBER(30) PRIMARY KEY, //(AUTO INCREMENT)
QUESTION NUMBER(30),  //설문의 질문고유번호 FK
USERID VARCHAR2(30),  // 유저KEY , FK
OPTION_ID NUMBER(30), //옵션 고유 번호 , FK
ANSWER VARCHAR2(200) //실제 답변
CONSTRAINT QA1 FOREIGN KEY(QUESTION)
      REFERENCES QUESTION_SURVEY(QUESTION),
CONSTRAINT QA2 FOREIGN KEY(USERID)
      REFERENCES USER(USERID),
CONSTRAINT QA3 FOREIGN KEY(USERID)
      REFERENCES QUESTION_OPTION(OPTION_ID),

TABLE1,2,3을 JOIN해서 파싱시키고 객관식이든 주관식이든 질문 등록하고 답변을 받아 올 수 있을 것 같습니다
VALUE값들은 TABLE3의  해당 고유번호를 가지고 폼을 넘겨주시면 될 것 같습니다

**--2 일 경우**
수기로 설문조사한 내역만 저장을 한다면
■SURVEY_QUESTION = 결과값만 담을 테이블
CREATE TABLE QUESTION_RESULT(
QUESTION_ID VARCHAR2(30) PRIMARY KEY, (AUTO INCREMENT)
USERID VARCHAR2(30),
TITLE VARCHAR2(30) NOT NULL,
DATETIME DATE DEFAULT SYSDATE,
QUESTION_NUM NUMBER(1000) NOT NULL, //(AUTO INCREMENT)
QUESTION VARCHAR2(30) NOT NULL,
RESULT VARCHAR2(50) NOT NULL,
CONSTRAINT FK_SURVEY_RESULT FOREIGN KEY(USERID)
      REFERENCES USER(USERID)
);

**Comment by rnin9** [comment]
1번방식으로 해서 설문조사 내용도 변경할 수 있게하고, option도 줄 수 있으면 최선이겠지만, 테이블이 복잡해질 수 도있어서 일단 2안으로 하는방식이 어떨까 싶네요. 설문조사 내용은 변하지 않는다고 가정하고, 2번 안으로 진행해서 사용자들의 성별, 나이, 전공/비전공자별 설문조사 통계때 사용할 수 있으면 좋을것 같습니다.

**Comment by Parkmsms** [comment]
생각해보니 ..
객관식 주관식 나누는 것보다 통계 시 객관식 항목까지 데이터를 빼오는 것이 
더 간편해 보여서 따로 구분 짓지는 않았습니다..

질문이 담긴 테이블
■QUESTION
> CREATE TABLE QUESTION(
> QUESTION_ID NUMBER(30) PRIMARY KEY,
> QUESTION VARCHAR2(30) NOT NULL 
> );


USER 테이블의 userid 컬럼을 참고하는 사용자의 설문조사의 답변
■QUESTION_ANSWER 
> CREATE TABLE QUESTION_ANSWER(
> ANSWER_ID NUMBER(30) PRIMARY KEY,
> QUESTION_ID NUMBER(30) NOT NULL,
> USERID VARCHAR2(30) NOT NULL,
> ANSWER VARCHAR2(30) NOT NULL,
> WRITEDATE DATE DEFAULT SYSDATE,
> CONSTRAINT FK_QA1 FOREIGN KEY (QUESTION_ID)
> REFERENCES QUESTION(QUESTION_ID),
> CONSTRAINT FK_QA2 FOREIGN KEY (USERID)	
> REFERENCES USERS(USERID)

);

**Comment by Parkmsms** [comment]
**통계를 위한 객관식 문항 20개이며 삭제, 수정되지 않는다에 가정한 테이블입니다..**
설문의 형식이 바뀌어 컬럼의 내용이 만약 바뀐다고 생각한다면 SURVEY 테이블에 
설문조사의 항목 고유번호 컬럼을 추가하고 테이블을 증설하는 
즉 그 항목의 고유번호에 맞는 테이블을 생성하면 될 것 같습니다..
SURVEY_ANSWER
```sql
CREATE TABLE SURVEY(
SURVEY_ID NUMBER(30) PRIMARY KEY,
SURVEY_TITLE VARCHAR2(30) NOT NULL
);
```

```sql
CREATE TABLE SURVEY_ANSWER(
 ANSWER_ID NUMBER(30) PRIMARY KEY,
 USERID VARCHAR2(30) NOT NULL,
 SURVEY_ID NUMBER(30) NOT NULL,
 ANSWER1 VARCHAR2(30) NOT NULL,
 ANSWER2 VARCHAR2(30) NOT NULL,
 ANSWER3 VARCHAR2(30) NOT NULL,
 ANSWER4 VARCHAR2(30) NOT NULL,
 ANSWER5 VARCHAR2(30) NOT NULL,
 ANSWER6 VARCHAR2(30) NOT NULL,
 ANSWER7 VARCHAR2(30) NOT NULL,
 ANSWER8 VARCHAR2(30) NOT NULL,
 ANSWER9 VARCHAR2(30) NOT NULL,
 ANSWER10 VARCHAR2(30) NOT NULL,
 ANSWER11 VARCHAR2(30) NOT NULL,
 ANSWER12 VARCHAR2(30) NOT NULL,
 ANSWER13 VARCHAR2(30) NOT NULL,
 ANSWER14 VARCHAR2(30) NOT NULL,
 ANSWER15 VARCHAR2(30) NOT NULL,
 ANSWER16 VARCHAR2(30) NOT NULL,
 ANSWER17 VARCHAR2(30) NOT NULL,
 ANSWER18 VARCHAR2(30) NOT NULL,
 ANSWER19 VARCHAR2(30) NOT NULL,
 ANSWER20 VARCHAR2(30) NOT NULL,
 WRITEDATE DATE DEFAULT SYSDATE,
 CONSTRAINT FK_SURVEY3 FOREIGN KEY (SURVEY_ID)
 REFERENCES SURVEY(SURVEY_ID),
 CONSTRAINT FK_SURVEY4 FOREIGN KEY (USERID)
 REFERENCES KTDS_USER(USERID)
);
```
ANSER_ID = 고유번호PK AUTO INCREMENT
SURVEY_ID = 설문조사의 고유 ID FK
```sql
SELECT * FROM SURVEY_ANSWER2 ORDER BY SURVEY_ID;
``` 
![image](https://user-images.githubusercontent.com/79435558/112429726-64b75980-8d80-11eb-9b06-df66ed75f9f7.png)


```sql
SELECT A.USERID,A.SURVEY_ID,B.SURVEY_TITLE
FROM survey_answer2 A, SURVEY2 B
WHERE A.SURVEY_ID = B.SURVEY_ID;
```
![image](https://user-images.githubusercontent.com/79435558/112429462-07230d00-8d80-11eb-9695-7aa43a0249f6.png)
