### ISSUE TITLE
Partner_Apply (지원)

### ISSUE THREAD

**Issue by rnin9** [rnin9/KT-ds-University-17th-web-application-project#17]
회원이 이력서로, 협력사에 지원하는 기능을 수행하는 지원 Table입니다. Constraint와 Column을 논의해 주세요

**Comment by rlarhkd** [comment]
Partner_apply_UserID varchar2(30) ,     /* 지원자 아이디*/
Partner_apply_PartnerID varchar2(30)  /* 협력사 아이디*/

**Comment by rlarhkd** [comment]
> > > ```sql
> > > CREATE TABLE PARTNER_APPLY(
> > >   Partner_Apply_UserID varchar2(30) not null ,      /* 지원자 아이디*/
> > >   Partner_Apply_PartnerID varchar2(30) not null,    /* 협력사 아이디*/
> > >   Partner_Apply_ResumeID varchar2(30) not null,     /* 이력서 아이디*/
> > >   Partner_Apply_Date Date default sysdate,          /* 지원날짜*/
> > >   Partner_Apply_State char(9) default '진행중',      /* 지원 상태*/
> > >   CONSTRAINT PK_Partner_Apply PRIMARY KEY (Partner_Apply_UserID, Partner_Apply_PartnerID),
> > >   CONSTRAINT FK_Partner_Apply_UserID FOREIGN KEY (Partner_Apply_UserID)
> > >   REFERENCES KT_USER(userID),
> > >   CONSTRAINT FK_Partner_Apply_PartnerID FOREIGN KEY (Partner_Apply_PartnerID) 
> > >   REFERENCES PARTNER(partnerLicenseNum),
> > >   CONSTRAINT FK_Partner_Apply_RuesumeID FOREIGN KEY (Partner_Apply_ResumeID)
> > >   REFERENCES RESUME(resumeID),
> > >   CONSTRAINT Partner_apply_State_chk check (Partner_Apply_State in ('진행중', '불합격', '합격'))
> > > );
> > > ```
> > >   1. 지원자 아이디와 협력사 아이디 하나만을 사용하여 프라이머리키로 사용하여 공고번호를 삭제하였습니다.
