### ISSUE TITLE
관리자 기능

### ISSUE THREAD

**Issue by rnin9** [rnin9/KT-ds-University-17th-web-application-project#2]
관리자 요구사항을 정리한 issue입니다.

**Comment by rnin9** [comment]
강민주입니다. 오늘 인터뷰 이후 요구사항들을 나름대로 정리해 봤습니다. 

### 회원관리
___
* 회원개인 정보 조회

  * 권한 별 정보 조회 **_-> 협약사에 대한 부분을 생각해봐야 할 것 같습니다._** 
  *  필요한 필터링을 통한 정보 검색
  *  회원 정보 수정


### 과정관리
___

* 교육과정 등록
  *  홈페이지에 등록해야하는 과정에 대한 세부사항 작성

### 게시판
___
*  Q & A 
   * Q&A 방식
* 수강 후기
  * 재직자에 대한  수강 후기 관리

### 수강관리
___
*  수강 등록

   * 홈페이지에 등록할 강의 설정, 노출되어야 하는 자료 설정

### 통계관리
___
* 데이터 시각화 , 통계
 * google chart ? , d3? ->**_어떤 자료에 대한 분석을 진행할 지 고민해야 할 것 같습니다._**

**Comment by rlarhkd** [comment]
> 
> ### 회원관리
> * 회원개인 정보 조회
>   
>   * 권한 별 정보 조회 **_-> 협약사별 관리자에게 보조 관리자?ID를 발급하여 각 소속회사 직원들의 정보를 볼수 있고 엑셀형식으로 자료를 추출하게 하는 것은 어떨까요? _**
>   * 필요한 필터링을 통한 정보 검색  
>   * 회원 정보 수정
>-----
> ### 과정관리
> * 교육과정 등록
>   
>   * 홈페이지에 등록해야하는 과정에 대한 세부사항 작성
>   **수요조사가 과정들의 인원 충족/불가 형식으로 속성을 만들어 이를 보고 충족시 관리자가 해당 과정의 강의 계획서를 등록하고 불가시에는 관리자가 삭제하는 방식으로 과정을 등록하는건 어떨까요?**
>
>  * 수강 등록
>   
>    * 홈페이지에 등록할 강의 설정, 노출되어야 하는 자료 설정 ->  **노출되어야 하는 자료의 경우 강사진의 경우에는 강사님께서 말씀하셨듯이 강사진의 정보는 등록이 안되게 해놓는것이  어떨까요?**
>   
>  ----------
> ### 수강관리
> * 수강신청내역 관리
> 
>   * **각 로우에 체크박스를 추가하여 관리자가 쉽게 승인상태를 변경**
>   
> * 수료관리
>   
>   * **강좌 유형, 단어, 날짜로  검색이 가능하게 하여 관리자가 쉽게 검색하게 하면 좋을 것 같습니다.**
> ---------
> ### 통계관리
> * 데이터 시각화 , 통계
>  
>   * google chart ? , d3? ->**_과정에 대한 사전수요조사에 대한 데이터를 추출하여 차트 형식으로 관리자에게 보여주는 것은 어떨까요._**
Duplicate of #

**Comment by rnin9** [comment]
@rlarhkd
- [x] 기능

적어주신 자료들과 내용을 표로 구성해봤습니다.  **'자세히' 를 클릭하시면 대략적인 설명이 나옵니다.** 



| 회원관리       	| 과정관리       	| 수강관리     	| 게시판관리 	| 통계관리         	|
|----------------	|----------------	|--------------	|------------	|------------------	|
| 정보조회	| 교육과정 	| 강의신청 	|Q & A          	| 설문조사 	|
| 이력서 관리    	| 수강등록 	| 강의수료     |            	|                  	|

<details>
    <summary>자세히</summary>


## 회원 관리
* 정보조회 
  회원 정보를 필터를 통해 검색하여 출력하고, 나온 계정에대한 조회, 수정, 삭제,  -> 이력서 조회도 가능하면 좋을거 같습니다.
* 이력서 관리
  홈페이지에 나올 이력서 항목 변경 및 관리, 출력 등을 할 수 있게 나누면 어떨까요?

## 과정관리
* 교육과정 
  수강등록에서 추가할 교육과정(curriculum) 자체에 대한 등록
* 수강등록
  홈페이지 배너및 사용자 페이지 수강관련 탭에 강의가추가 될 수 있도록 구성함

## 게시판 관리
* Q & A 관리 
  회원 / 비회원 Q&A를 따로 구성하여 진행하면 1:1상담과 같은 기능을 대신 수행할 수 있을것 같습니다.

## 통계관리
* 설문조사
  과정에 대한 사전수요조사에 추가하여 설문조사 용지를 관리자에게 미리 받아 확인하여 통계화할 데이터들을 생각해보면 좋을것 같습니다.

</details> <br>
한가지 우려되는점은 위와 같이 만들었을 때, 기존 페이지와 완전 동일한 형태를 가질까 살짝 걱정되긴합니다!

**Comment by penglingss** [comment]
1. 과장님이 협력사로 저희 이력서 보낸다고 하신게 협력사에 일일이 파일들을 보내는거라면 홈페이지에 이력서 업로드해놓고 협력사가 찾아볼 수 있게(협력사 로그인을 구현한다면) 하는게 좋을거같습니다.

2. 관리하기 편하게 1:1 문의는 회원가입을 해야만 작성할 수 있게 하는게 좋을거같습니다. 현재 홈페이지에 오픈톡방 링크를 올려두셨길래 챗봇을 잠시 생각해봤습니다(무시해주세요).

3.  설문조사 통계의 목적이 무엇인지 제가 잘 이해하지 못해서 좀 더 생각해보겠습니다.

4.  기존 페이지의 기능을 따라가야해서 형태는 비슷하게 나올거같지만 UI 구성 잘 하고 데이터 조회할 때 느리고 페이지 자체가 무겁다고 하셨는데 그게 DB문제인지, 성능 개선을 어떻게 해야할지는 아직 잘 모르겠지만 이 점도 고려해서 개발하면 괜찮을것같습니다.

**Comment by clair-deLune** [comment]
**교육과정**
많은 검색 조건에 대해서 필요 없다는 의견이 있었을 정도였지만 실제로 있어야 할 기능이기 때문에  접히는 방식으로 평상시엔 가려져 있되, 펼치면 모든 기능을 모두 사용할 수 있도록 구성하는 것이 어떨까 생각합니다.
다음과 같은 방식으로 구현하면 좋지 않을까 생각했습니다.
![image](https://user-images.githubusercontent.com/79443607/109108552-2164cd80-7777-11eb-8e3a-ccf1ceabc1d2.png)

**이력서 관리**
보통 이력서를 제출 받을 때 서버시간을 기준으로 제출을 받는데, 기업에 따라 지원 완료의 기준이 조금씩 다르다는 느낌을 받았습니다.  서버시간에 맞춰서 딱 끊어 서류를 받을 것인지 서버의 부담에 따라 지원자가 몰려 에러가 날때를 대비하여 십분 가량의 주어진 여유 시간 동안 (5분?) 제출을 허용한다던지 하는 방식을 채택한 곳도 있었습니다. 이를 적용하려면 담당자 분께 정책을 문의 드려 조금 더 여유있는 지원이 가능하게 하는 것도 괜찮은 방식이리라고 생각합니다.  

**협력사 정보 접근**
협력사 전용 로그인 창과 페이지를 신설하여 간략한 UI를 제공하는 것이 제작과 보수가 간단하지 않을까 싶습니다. 그리고 이력서를 협약사 쪽에서 접근하여 열람하는 것도 좋은 방식이지만, 과장님께서 담당자간에 이메일과 연락을 통해 직접 이력서를 보내시는 것이 상대 담당자가 신경써서 읽어 볼 가능성이 높은 메리트가 커다란 방식이기 때문에 데이터 접근 구축에 무리가 있다면 그 비중을 줄여도 커다란 손해는 없지 않나 생각합니다.

**Comment by rlarhkd** [comment]
**협력사 정보 접근**
위에 말씀 하셨던 내용들처럼 간단하게 ui를 제공하고 중요한 이력서나 정보등은 직접 전달을 통해 전달하는 것이 더 효과적일것 같습니다.

**설문조사**
인터뷰때 말씀하셨던것 같은데 모든 과정을 개설할때에는 항상 사전 수요조사를 통해 해당과정의 수요 인원이  특정인원이상을 충족해야지 개설가능하다고 이해했습니다. 
[(최종)kt+ds+수요조사_수강생용.pdf](https://github.com/rnin9/KT-ds-University-17th-web-application-project/files/6053967/kt%2Bds%2B._.pdf)
현재는 위파일과 함께 공지를 직접 올려야하는데 이를 홈페이지 메인에 추가하고 사용자들이 입력하게 하여 프로그램상으로 처리하여 관리자가 볼 수 있게 하면 좋을것 같습니다.


**알림 기능**
![제목 없음](https://user-images.githubusercontent.com/79435550/109381540-5cedcc00-791e-11eb-99ea-027d38fc38e0.png)
위 그림 처럼 관리자가 사용자의 지원 결과, 사용자가 문의한 내용에 대하여 답변 ,진행상태등이 업데이트되었을때 이를 알림식으로 사용자들에게 보내는 기능을 추가하는 것은 어떨까요? 중요한 지원 혹은 신청과정 결과 에 관련한 내용등은 이메일도 같이 보내고 이외에 문의나 공지사항등이 업데이트되었을때 알림을 보내면 좋을것 같습니다..

**Comment by rnin9** [comment]
## 기본기능
* 회원관리기능
*  과정관리기능
* 수강관리기능
* 게시판 관리기능
* 통계관리기능
## 부가기능
* 알림기능 https://github.com/rnin9/KT-ds-University-17th-web-application-project/issues/2#issuecomment-787039132
* 취업률, 취업가능 기업 통계에 대한 시각화
* 필터링 기능의 선택적 단순화 https://github.com/rnin9/KT-ds-University-17th-web-application-project/issues/2#issuecomment-785632060
* 협력사 접근 관리
<details>
    <summary>기능소개</summary>

<br>
**'자세히' 를 클릭하시면 기능에대한 설명이 나옵니다.** 



| 회원관리       	| 과정관리       	| 수강관리     	| 게시판관리 	| 통계관리         	|
|:----------------:	|:----------------:	|:--------------:	|:------------:	|:------------------:	|
| 정보조회	| 교육과정 	| 강의신청 	|Q & A          	| 설문조사 	|
| 이력서 관리    	| 수강등록 	| 강의수료     |            	|                  	|
|   	| 수강후기 관리	| 강의수료     |            	|                  	|
<details>
    <summary>자세히</summary>


## 회원 관리
* 정보조회 
  회원 정보를 필터를 통해 검색하여 출력하고, 나온 계정에대한 조회, 수정, 삭제,  **_-> 이력서 조회도 가능하면 좋을거 같습니다._**
* 이력서 관리
  홈페이지에 나올 이력서 항목 변경 및 관리, 출력 등을 할 수 있게 나누면 어떨까요?

## 과정관리
* 교육과정 
  수강등록에서 추가할 교육과정(curriculum) 자체에 대한 등록
* 수강등록
  홈페이지 배너및 사용자 페이지 수강관련 탭에 강의가추가 될 수 있도록 구성함
## 수강관리
* 신청강의 관리
  강의를  신청한 회원에 대한 관리
* 강의수료
  강의수료를 완료한 회원 관리 **_-> 협약사도 해당데이터에 접근가능_**
  수료증발급, 취업한 기업, 이력서, 성적에 대한 부분을 확인
## 게시판 관리
* Q & A 관리 
  회원 / 비회원 Q&A를 따로 구성하여 진행하면 1:1상담과 같은 기능을 대신 수행할 수 있을것 같습니다.

## 통계관리
* 설문조사
  과정에 대한 사전수요조사에 추가하여 설문조사 용지를 관리자에게 미리 받아 확인하여 통계화할 데이터들을 생각해보면 좋을것 같습니다.

</details> <br>
