### ISSUE TITLE
RESUME_CAREER (경력, 교육내용 관리)

### ISSUE THREAD

**Issue by yeohu0910** [rnin9/KT-ds-University-17th-web-application-project#23]
이력서 테이블을 참조하여 경력내용과 교육기관에서의 교육내용을 담은 테이블입니다. Constrain와 Column을 논의하세요.

**Comment by yeohu0910** [comment]
> > ```sql
> > CREATE TABLE RESUME (
> >   careerID varchar2(10) not null,		
> >   careerUser varchar2 (30) not null,		
> >   careerResume varchar2(30) not null,
> >   careerCenter varchar2(30) not null,   // 교육기관 또는 소속했던 회사명
> >   careerDate varchar2(30) not null,     // 교육기간 또는 경력기간
> >   careerContent varchar2(50) not null,  //교육내용 또는 주요 경력사항
> >   careerHour varchar2(5),               //교육시간 (교육 내용에 해당)
> >   careerType varchar2(10) not null,    // 고용 형태 (경력에만 해당, 정규/계약으로 구분)
> >   careerPosition varchar2(20),         // 직위 (경력에만 해당)
> >   careerOther varchar2(30),             // 비고 및 재직 상태 확인(재직, 퇴사)
> >   careerCheck char(1) default 'C',     // 교육내용과 경력사항을 구분하는 컬럼
> >   CONSTRAINT PK_CAREER PRIMARY KEY (careerID),
> >   CONSTRAINT FK_CAREER_USER FOREIGN KEY (careerUser) 
> >   REFERENCES USER(userID),             // FK 설정
> >   CONSTRAINT FK_CAREER_RESUME FOREIGN KEY (careerResume) 
> >   REFERENCES RESUME(resumeID),         // FK 설정
> >  CONSTRAINT CHECK_CE CHECK(careerCheck IN ('C', 'E'))
> > // 경력사항은 C, 교육내용은 E로 구분하게 했습니다.
> >  );
> > ```
> > 
> > 
> > 
> > 1.  RESUME 테이블에서 구분한 내용으로, 경력사항과 교육내용을 하나의 테이블로 합쳤습니다.
> > 2.  USER 테이블과 RESUME테이블의 내용을 FK로 담았고 작동하도록 했습니다.
> > 3.  경력사항과 교육내용 관련 내용을 한번에 관리하기 때문에, C또는 E를 확인하여 체크하도록 했는데, 관련 내용은 다양한 의견 부탁드립니다. 
> > 4. 추가 사항이나 의견 말씀해주시면 바로 반영해보도록 하겠습니다. 감사합니다.

**Comment by rnin9** [comment]
PK를 careerID로 사용하지 않고, (careerUser, careerResume, careerDate) 의 Composite Key로 사용하면 되지않을까 생각합니다. 이외에는 잘 구성해 주신 것으로 보입니다.

**Comment by yeohu0910** [comment]
> > ```sql
> > CREATE TABLE RESUME_CAREER (	
> >   careerUser varchar2 (30) not null,		
> >   careerResume varchar2(30) not null,
> >   careerCenter varchar2(30) not null,   // 교육기관 또는 소속했던 회사명
> >   careerDate varchar2(30) not null,     // 교육기간 또는 경력기간
> >   careerContent varchar2(50) not null,  //교육내용 또는 주요 경력사항
> >   careerHour varchar2(5),               //교육시간 (교육 내용에 해당)
> >   careerType varchar2(10) not null,    // 고용 형태 (경력에만 해당, 정규/계약으로 구분)
> >   careerPosition varchar2(20),         // 직위 (경력에만 해당)
> >   careerOther varchar2(30),             // 비고 및 재직 상태 확인(재직, 퇴사)
> >   careerCheck char(1) default 'C',     // 교육내용과 경력사항을 구분하는 컬럼
> >   CONSTRAINT PK_CAREER PRIMARY KEY (careerUser, careerResume, careerDate),
> >   CONSTRAINT FK_CAREER_USER FOREIGN KEY (careerUser) 
> >   REFERENCES USER(userID),             // FK 설정
> >   CONSTRAINT FK_CAREER_RESUME FOREIGN KEY (careerResume) 
> >   REFERENCES RESUME(resumeID),         // FK 설정
> >   CONSTRAINT CHECK_CE CHECK(careerCheck IN ('C', 'E'))
> > // 경력사항은 C, 교육내용은 E로 구분하게 했습니다.
> >  );
> > ```
> > 
> > 
> > 1.  일단 @rnin9 님이 말씀해 주신대로 PK 설정값을 수정해서 반영했습니다.
> > 2.  추가 사항이나 의견 말씀해주시면 바로 반영해보도록 하겠습니다.

**Comment by yeohu0910** [comment]
> > ```sql
> > CREATE TABLE RESUME_CAREER (	
> >   careerID varchar2(30) not null,	
> >   careerResume varchar2(30) not null,
> >   careerCenter varchar2(30) not null,   /* 교육기관 또는 소속했던 회사명 */
> >   careerDate varchar2(30) not null,     /* 교육기간 또는 경력기간 */
> >   careerContent varchar2(50) not null,  /* 교육내용 또는 주요 경력사항 */
> >   careerHour varchar2(5),               /* 교육시간 (교육 내용에 해당) */
> >   careerType varchar2(10),    /* 고용 형태 (경력에만 해당, 정규/계약으로 구분) */
> >   careerPosition varchar2(20),         /* 직위 (경력에만 해당) */
> >   careerOther varchar2(30),             /* 비고 및 재직 상태 확인(재직, 퇴사) */
> >   careerCheck char(1) default 'C',     /* 교육내용과 경력사항을 구분하는 컬럼 */
> >   CONSTRAINT PK_CAREER PRIMARY KEY (careerID, careerResume),
> >   CONSTRAINT FK_CAREER_RESUME FOREIGN KEY (careerResume) 
> >   REFERENCES RESUME(resumeID),         /* FK 설정 */
> >   CONSTRAINT CHECK_CE CHECK(careerCheck IN ('C', 'E'))
> > /* 경력사항은 C, 교육내용은 E로 구분하게 했습니다. */
> >  );
> > ```
> > 
> > 
> > 1.  3월24일 회의내용 반영했습니다.
> > 2.  추가 사항이나 의견 말씀해주시면 바로 반영해보도록 하겠습니다.

**Comment by yeohu0910** [comment]
> > ```sql
> > CREATE TABLE RESUME_CAREER (	
> >   careerID varchar2(30) not null,	
> >   careerResume varchar2(30) not null,
> >   careerCenter varchar2(30) not null,   /* 교육기관 또는 소속했던 회사명 */
> >   careerDate varchar2(30) not null,     /* 교육기간 또는 경력기간 */
> >   careerContent varchar2(50) not null,  /* 교육내용 또는 주요 경력사항 */
> >   careerHour varchar2(5),               /* 교육시간 (교육 내용에 해당) */
> >   careerType varchar2(10),    /* 고용 형태 (경력에만 해당, 정규/계약으로 구분) */
> >   careerPosition varchar2(20),         /* 직위 (경력에만 해당) */
> >   careerOther varchar2(30),             /* 비고 및 재직 상태 확인(재직, 퇴사) */
> >   careerCheck char(1) default 'C',     /* 교육내용과 경력사항을 구분하는 컬럼 */
> >   CONSTRAINT PK_CAREER PRIMARY KEY (careerID, careerResume),
> >   CONSTRAINT FK_CAREER_RESUME FOREIGN KEY (careerResume) 
> >   REFERENCES RESUME(resumeID),         /* FK 설정 */
> >   CONSTRAINT CHECK_CAREER CHECK(careerCheck IN ('C', 'E'))
> > /* 경력사항은 C, 교육내용은 E로 구분하게 했습니다. */
> >  );
> > ```
> > 
> > 
> > 1.  3월25일 회의내용 반영했습니다. (CHECK_CAREER 로 변경)
> > 2.  추가 사항이나 의견 말씀해주시면 바로 반영해보도록 하겠습니다.
