### ISSUE TITLE
RESUME_CERTIFICATE (자격증)

### ISSUE THREAD

**Issue by yeohu0910** [rnin9/KT-ds-University-17th-web-application-project#24]
이력서 테이블을 참조하여 자격증을 관리하는 테이블입니다. Constrain와 Column을 논의하세요.

**Comment by yeohu0910** [comment]
> > ```sql
> > CREATE TABLE RESUME_CERTIFICATE (
> >   cerID varchar2(10) not null,		
> >   cerUser varchar2(30) not null,		
> >   cerResume varchar2(30) not null,
> >   cerName varchar2(30) not null, // 외국어명(영어, 중국어), 자격증명(정보처리기사, SQLD)
> >   cerTest varchar2(30),          // 시험명 (TOEIC, TOFLE) (외국어 자격증에만 해당)
> >   cerScore varchar2(20),         // 취득점수/등급 (990) (외국어 자격증에만 해당)
> >   cerEnforcement varchar2(20) not null, // 시행처
> >   cerDate varchar2(30) not null, // 취득일자
> >   cerOther varchar2(20),         // 비고
> >   cerCheck char(1) default 'C',  // 자격증과 외국어 자격증을 구분
> >   CONSTRAINT PK_CERTIFICATE PRIMARY KEY (cerID),
> >   CONSTRAINT FK_CERTIFICATE_USER FOREIGN KEY (cerUser) 
> >   REFERENCES USER(userID),             // FK 설정
> >   CONSTRAINT FK_CERTIFICATE_RESUME FOREIGN KEY (cerResume) 
> >   REFERENCES RESUME(resumeID),         // FK 설정
> >   CONSTRAINT CHECK_CE CHECK(careerCheck IN ('C', 'F'))
> > // 자격증은 C, 외국어 자격증은 F로 구분하게 했습니다.
> >  );
> > ```
> > 
> > 
> > 
> > 1.  RESUME 테이블에서 구분한 내용으로, 자격증과 외국어 자격증을 하나의 테이블로 합쳤습니다.
> > 2.  USER 테이블과 RESUME테이블의 내용을 FK로 담았고 작동하도록 했습니다.
> > 3.  자격증과 외국어 자격증 관련 내용을 한번에 관리하기 때문에, C또는 E를 확인하여 체크하도록 했는데, 관련 내용은 다양한 의견 부탁드립니다. 
> > 4. 추가 사항이나 의견 말씀해주시면 바로 반영해보도록 하겠습니다. 감사합니다.

**Comment by rnin9** [comment]
해당 부분도 PK를 cerID로 설정하기보다, (cerUser, cerResume, cerDate)의 3개로 나누어 pk를 구성하면 좋을것 같습니다. attribute명은 사실 줄임말을 지양하라고하는데, 속성명을 정하기 어렵긴하네요.... certificateOwner 이런식으로 이름을 정해주면 좀 더 이해하기 쉬운 컬럼명이 될것 같습니다. 

cerName과 cerTest의 의미전달이 조금 직관적이지 못한거 같아서, certificateCriteria로 영어/중국어/자격증명 등을 구분하는 속성으로 나타내고, cerTest를 certificateName으로 해서 자격증 이름을 주면 어떨까 싶습니다.

**Comment by yeohu0910** [comment]
> > ```sql
> > CREATE TABLE RESUME_CERTIFICATE (
> >   certificateUser varchar2(30) not null,		
> >   certificateResume varchar2(30) not null,
> >   certificateCriteria varchar2(30) not null, // 외국어명(영어, 중국어), 자격증명(정보처리, SQL)
> >   certificateName varchar2(30) not null,          // 시험명 (TOEIC, TOFLE, 기사, 산업기사, SQLD)
> >   certificateScore varchar2(20),         // 취득점수/등급 (990) (외국어 자격증에만 해당)
> >   certificateEnforcement varchar2(20) not null, // 시행처
> >   certificateDate varchar2(30) not null, // 취득일자
> >   certificateOther varchar2(20),         // 비고
> >   certificateCheck char(1) default 'C',  // 자격증과 외국어 자격증을 구분
> >   CONSTRAINT PK_CERTIFICATE PRIMARY KEY (certificateUser, certificateResume, certificateDate),
> >   CONSTRAINT FK_CERTIFICATE_USER FOREIGN KEY (certificateUser) 
> >   REFERENCES USER(userID),             // FK 설정
> >   CONSTRAINT FK_CERTIFICATE_RESUME FOREIGN KEY (certificateResume) 
> >   REFERENCES RESUME(resumeID),         // FK 설정
> >   CONSTRAINT CHECK_CE CHECK(certificateCheck IN ('C', 'F'))
> > // 자격증은 C, 외국어 자격증은 F로 구분하게 했습니다.
> >  );
> > ```
> > 
> > 
> > 
> > 1.  @rnin9 님이 말씀해주신 의견대로 attribute 명 수정해서 반영했습니다.
> > 2. 추가 사항이나 의견 말씀해주시면 바로 반영해보도록 하겠습니다. 감사합니다.

**Comment by yeohu0910** [comment]
> > ```sql
> > CREATE TABLE RESUME_CERTIFICATE (		
> >   certificateResume varchar2(30) not null,
> >   certificateCriteria varchar2(30) not null, /* 외국어명(영어, 중국어), 자격증명(정보처리, SQL) */
> >   certificateName varchar2(30) not null,          /* 시험명 (TOEIC, TOFLE, 기사, 산업기사, SQLD)*/
> >   certificateScore varchar2(20),         /* 취득점수/등급 (990) (외국어 자격증에만 해당)*/
> >   certificateEnforcement varchar2(20) not null, /* 시행처 */
> >   certificateDate varchar2(30) not null, /* 취득일자 */
> >   certificateOther varchar2(20),         /* 비고 */
> >   certificateCheck char(1) default 'C',  /* 자격증과 외국어 자격증을 구분 */
> >   CONSTRAINT PK_CERTIFICATE PRIMARY KEY (certificateResume, certificateName, certificateDate),
> >   CONSTRAINT FK_CERTIFICATE_RESUME FOREIGN KEY (certificateResume) 
> >   REFERENCES RESUME(resumeID),         /* FK 설정 */
> >   CONSTRAINT CHECK_CE CHECK(certificateCheck IN ('C', 'F'))
> > // 자격증은 C, 외국어 자격증은 F로 구분하게 했습니다.
> >  );
> > ```
> > 
> > 
> > 
> > 1.  3월 24일 회의내용 반영했습니다.
> > 2. 추가로, **certificateCheck**관련해서, @rnin9 님께서 자격증과 외국어 자격증 내용을 구분할 때, <br> 추가 컬럼으로 확인하지 않고 **certificateCriteria**에서 **외국어**와 **자격증**으로 구분해서 확인하자는 의견을 주셨습니다. 관련사항 내일 다시 토의해서 반영하겠습니다.

**Comment by yeohu0910** [comment]
> > ```sql
> > CREATE TABLE RESUME_CERTIFICATE (		
> >   certificateResume varchar2(30) not null,
> >   certificateName varchar2(30) not null, /* 자격증명(정보처리기사, SQLD) */
> >   certificateEnforcement varchar2(20) not null, /* 시행처 */
> >   certificateDate varchar2(30) not null, /* 취득일자 */
> >   CONSTRAINT PK_CERTIFICATE PRIMARY KEY (certificateResume, certificateName),
> >   CONSTRAINT FK_CERTIFICATE_RESUME FOREIGN KEY (certificateResume) 
> >   REFERENCES RESUME(resumeID)          /* FK 설정 */
> >  );
> > ```
> > 
> > 
> > 
> > 1.  3월 25일 회의내용 반영했습니다. **자격증 테이블**과 **외국어 자격증 테이블**을 따로 작성하기 때문에,<br> 현재 **RESUME_CERTIFICATE** 테이블을 **자격증** 테이블로 사용하고, <br> **RESUME_FOREIGN** 테이블을 추가로 작성해서 **외국어 자격증**을 관리하도록 하겠습니다.
> > 2.  **자격증 이름**이 **정보처리기사, SQLD**처럼 명확하게 확인 가능하기 때문에 **CRITERIA** 컬럼을 삭제했고, <br> **PK** 설정을 다시 해서 **certificateResume, certificateName**으로 복합키 설정 했습니다.  <br> 추가로 **비고** 컬럼도 삭제했습니다. 
> > 3. 추가 의견 부탁드립니다.
