### ISSUE TITLE
RESUME_PROJECT (프로젝트 내용 관리)

### ISSUE THREAD

**Issue by yeohu0910** [rnin9/KT-ds-University-17th-web-application-project#25]
이력서 테이블을 참조하여 프로젝트 내용을 담은 테이블입니다. Constrain와 Column을 논의하세요.

**Comment by yeohu0910** [comment]
> > ```sql
> > CREATE TABLE RESUME_PROJECT (
> >   proID varchar2(10) not null,		
> >   proUser varchar2(30) not null,		
> >   proResume varchar2(30) not null,
> >   proEnforcement varchar2(20),     // 기관 
> >   proName varchar2(30),            // 프로젝트명
> >   proDev varchar2(50),             // 개발환경 및 사용기술
> >   proContent varchar2(200),        // 프로젝트 소개
> >   proRole varchar2(200),           // 담당한 역할
> >   CONSTRAINT PK_PROJECT PRIMARY KEY (proID),
> >   CONSTRAINT FK_PROJECT_USER FOREIGN KEY (proUser) 
> >   REFERENCES USER(userID),         // FK 설정
> >   CONSTRAINT FK_PROJECT_RESUME FOREIGN KEY (proResume) 
> >   REFERENCES RESUME(resumeID),     // FK 설정
> >  );
> > ```
> > 
> > 
> > 
> > 1.  RESUME 테이블에서 구분한 내용으로, 프로젝트 관련 내용을 하나의 테이블로 분리했습니다.
> > 2.  USER 테이블과 RESUME테이블의 내용을 FK로 담았고 작동하도록 했습니다.
> > 3. 추가 사항이나 의견 말씀해주시면 바로 반영해보도록 하겠습니다. 감사합니다.

**Comment by rnin9** [comment]
PK를 proID로 사용하지 않고, (proUser, proResume, proName)의 3가지 속성으로 구성하면 좋을 것 같습니다. 새로운 속성으로 projectURL을 만들어서 만든 프로젝트의 시연영상 혹은 github 주소를 담게 해주면어떨까 생각해봅니다.

**Comment by yeohu0910** [comment]
> > ```sql
> > CREATE TABLE RESUME_PROJECT (
> >   projectUser varchar2(30) not null,		
> >   projectResume varchar2(30) not null,
> >   projectEnforcement varchar2(20),     // 기관 
> >   projectName varchar2(30),            // 프로젝트명
> >   projectDev varchar2(50),             // 개발환경 및 사용기술
> >   projectContent varchar2(200),        // 프로젝트 소개
> >   projectRole varchar2(200),           // 담당한 역할
> >   projectURL varchar2(200),            // 프로젝트 관련 링크 (깃허브 등)
> >   CONSTRAINT PK_PROJECT PRIMARY KEY (projectUser, projectResume, projectName),
> >   CONSTRAINT FK_PROJECT_USER FOREIGN KEY (projectUser) 
> >   REFERENCES USER(userID),         // FK 설정
> >   CONSTRAINT FK_PROJECT_RESUME FOREIGN KEY (projectResume) 
> >   REFERENCES RESUME(resumeID),     // FK 설정
> >  );
> > ```
> > 
> > 
> > 
> > 1.  @rnin9 님이 말씀해주신 의견 반영했습니다.
> > 2.  추가 사항이나 의견 말씀해주시면 바로 반영해보도록 하겠습니다. 감사합니다.

**Comment by yeohu0910** [comment]
> > ```sql
> > CREATE TABLE RESUME_PROJECT (	
> >   projectResume varchar2(30) not null,
> >   projectEnforcement varchar2(20),     /* 기관 */
> >   projectName varchar2(30),            /* 프로젝트명 */
> >   projectDev varchar2(50),             /* 개발환경 및 사용기술 */
> >   projectContent varchar2(200),        /* 프로젝트 소개 */
> >   projectRole varchar2(200),           /* 담당한 역할 */
> >   projectURL varchar2(200),            /* 프로젝트 관련 링크 (깃허브 등) */
> >   CONSTRAINT PK_PROJECT PRIMARY KEY (projectResume, projectName),
> >   CONSTRAINT FK_PROJECT_RESUME FOREIGN KEY (projectResume) 
> >   REFERENCES RESUME(resumeID)      /* FK 설정 */
> >  );
> > ```
> > 
> > 
> > 
> > 1.  3월 24일 회의 내용 반영했습니다.
> > 2.  추가 사항이나 의견 말씀해주시면 바로 반영해보도록 하겠습니다. 감사합니다.
