### ISSUE TITLE
Table 정의를 위한 E-R 모델 작성

### ISSUE THREAD

**Issue by rnin9** [rnin9/KT-ds-University-17th-web-application-project#5]
안녕하세요! 민주입니다. 요구사항이 8일자로 마무리 되었습니다.<br>
이에따라 Table 정의서를 저희가 작성해야 하고 이는 저희가 프로젝트에서 사용할 SQL 작성을 위해 중요합니다.  먼저 테이블에 필수적으로 나타나야 하는 부분은 다음과 같습니다.

## 테이블 정의시 필수 목록 
* 테이블의 이름
* 속성( Attribute )
*  Domain
*  Constraint (PK, FK)
<br>

위와 같이 테이블을 정의를 하기 위해서 필요한 사항이 있는데,  **개체-관계 모델 (E-R Model)** 입니다. 이는 저번에 설명 드렸던 것 처럼 개체간의 관계를 표현하며, 이는 아래 예시와 같이 표현됩니다. <br> 

![image](https://user-images.githubusercontent.com/62874963/110306497-4132a600-8041-11eb-841f-f4d8953aaf71.png)
<br>

여기서 왜 개체 관계 모델이 필요하냐 라고 생각하실 수 있는데, 이는 Entity와 Relation(관계성), attribute를 요구사항에서 뽑아내는 과정이기 때문입니다.
___
## E-R 모델 작성방법

<details>
<summary> 방법 </summary>
<img src="https://user-images.githubusercontent.com/62874963/110308444-750ecb00-8043-11eb-8e5b-b11e98d3c552.png" width="700" height="450" />

위는 요구사항 명세의 #1 사용자와 #2 관리자' 부분에서 가져온 내용들입니다. 
상세한 사항은 해당 이슈에서 확인 하시면 되고, 여기서 눈에 가장 잘 보이는 로그인, 회원가입시 사용될 수 있어 Entity로 뽑아 낼 수 있는 **'회원'**, 수강신청시 사용될 Entity로 **'강의'** 를  Entity로 선정하고 뽑아 봅니다. <br>

![image](https://user-images.githubusercontent.com/62874963/110309799-206c4f80-8045-11eb-924d-9439b93048ec.png)
<br>

테이블들이 연관이 있다면 이어주는데, 연관이 있으면 **'Relation(관계성)'** 이 생기는 것이므로, 안에 관계를 적어줍니다. 

![image](https://user-images.githubusercontent.com/62874963/110310219-a4263c00-8045-11eb-936d-a34b43e77fae.png)

<br>

생각나는 속성들을 적어줍니다. 여기서 key로 사용하고자 하는 컬럼에 밑줄을 쳐 줍니다. <br>

<img src="https://user-images.githubusercontent.com/62874963/110311427-1d725e80-8047-11eb-9f83-d63384b08af0.png" width="600" height="300"/>

<br>

4. 나머지 사용자, 관리자 요구사항들을 참조하면서 모두 만족할 때까지 작성해 나갑니다. 

</details>

## 궁금할 수도 있는 사항

<details>
<summary> Q & A </summary>

> **Q1. 작성을 꼭 컴퓨터로 해야하나요?** 
>
> 작성방식은 무관하며, 손으로 그리셔도 되고 아니면 ppt를 사용하셔서 그리셔도되고, 방법은 상관없습니다. 사용자와 관리자요구사항을 참조하면서 "직접" 작성하시는것에 의미를 두시면됩니다. 이것이 완료되면, 맨 위에서 설명한 테이블 정의를 빠르게 진행할 수 있습니다.

> 
> **Q2.  E-R 모델링 이거 꼭 해야하나요?** 
>
> 작은 프로젝트라면 굳이 ER 모델링 필요없이 바로 테이블이 튀어나올 수 있겠지만, 규모가 커지면 필요하다 생각합니다. 
>무엇보다 요구사항을 보고 바로 테이블을 정의하라고 한다면 아무래도 너무 막연하기도 하고, 실제로 빠르게 테이블정의를 하기 어려웠습니다. 요구사항에 알맞게 작성하기 위함, 또 결정된 E-R모델로 테이블 정의를 좀 더 쉽게 진행하기 위함 이라고 생각하시면 좋을것 같습니다. 추가적으로 말씀드리면! 사용자 및 관리자를 나누어서 E-R모델을 생각하실 것이 아니라, 둘의 요구사항을 모두 만족할 수 있는 E-R모델을 작성하셔야 합니다.

> **Q3. 언제까지 하는게 좋을까요?** 
>
> 생각하는게 오래 걸릴 수도 있겠지만, 너무 골치아프게 생각하지 마시고 시간 오래 들일 필요없이, 요구사항에 만족하며 작성하겠다. 라고 생각하시면 좋을것 같습니다. 
> 9명이서 작성한것들을 비교하다 보면 내가 생각하지 못했던 것들을 볼 수 있고, 금방 만들수 있다 생각합니다. 해당 이슈 아래에 본인이 만든 E-R 모델을 코멘트로 달아주세요. 아무래도 E-R 모델링이 잘만들어지면 금방 테이블 정의를 진행할 수 있고, 목표에 근사하게 14일까지 테이블정의를 하기 위해 "12일"까지 해주시는게 좋아보입니다! 
> 

> **Q4. 틀리면 어떡하죠 쓰기 무서워요.**
>
> 원래 틀리면서 하는것이고, 해봐야 늘수 있습니다! 일단 작성해 보시고 그래도 힘들다면 개인적으로도 구글링을 해본 뒤, 작성하시면 도움이 될겁니다!
> 

> **Q5. 조장님 안쉬나요**
> 이제 놀러갑니다.
</details>
<br>
작성하시다가 요구사항이 이상하다 라고 판단 될 수 도 있고, 사용자 관리자가 서로 맞지않는 부분도 나올거라 생각하고 있습니다. 
이럴 경우, 다시 돌아가서 새로운 이슈에 코멘트로 이야기를 나눠 보고 조정해 나가면 됩니다. <br><br>
팀원 모두가 같이 잘  해쳐나간다면 좋은 결과가 있을것이라고 생각합니다! 문제가 되는 부분이나 이렇게 했으면 좋겠다 생각하시면 언제든지 이야기해주세요! 감사합니다.

**Comment by rnin9** [comment]
## E-R Modeling 1 
먼저 보기 쉽게 하기위해, Entity, Relation, Key Attribute만으로 구성된 E-R diagram을 만들어 봤습니다.
 주황색은 Entity, 노란색은 Weak Entity, 보라색은 Relationship, 빨간색은 recursive Relationship, 파란색은 identifying Relationship(식별관계), 회색은 (Key) Attribute입니다. <br/><br/>
![ER modeling1](https://user-images.githubusercontent.com/62874963/110792663-03d74e00-82b7-11eb-949e-94662197d690.png)
<br/><br/>

## 속성을 추가한 E-R Modeling
위와 동일하지만 속성을 더 추가했습니다. 당장 생각나는 속성들만 적었는데, 실제로 Table마다 Issue를 만들어서 팀원들이 같이 생각해 봐야할 것 같습니다.  <br><br>
![ER modeling2](https://user-images.githubusercontent.com/62874963/110793544-14d48f00-82b8-11eb-80cc-dfb3f257746d.png)

**Comment by ksh0310** [comment]
생각나는 대로 작성해봤는데 잘 작성한 건지 모르겠네요..
![image](https://user-images.githubusercontent.com/79489832/110794797-777a5a80-82b9-11eb-8422-ed8f1c87b98b.png)

**Comment by penglingss** [comment]
공지, 설문/통계, 협력사는 어떻게 해야할지 몰라서 저렇게 두었습니다.

![Untitled Diagram (1)](https://user-images.githubusercontent.com/56222478/110873208-93f7b080-8314-11eb-9a0f-959211c6d384.png)

**Comment by yeohu0910** [comment]
나름대로 나눠봤는데 맞게 한건지 잘 모르겠습니다.
![ERD](https://user-images.githubusercontent.com/79436054/110890336-2d35bf80-8333-11eb-8f2a-fa029c25e425.PNG)

**Comment by Parkmsms** [comment]
![E-R MODEL](https://user-images.githubusercontent.com/79435558/110892060-a97dd200-8336-11eb-8077-89fdf4d5b7ce.png)
생각나는 대로 해봤습니다..

**Comment by lovetmfqud** [comment]
![KakaoTalk_20210312_173947191](https://user-images.githubusercontent.com/79437560/110914708-13f43980-835a-11eb-9acf-df5f9105daea.jpg)

**Comment by rlarhkd** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/79435550/110926466-c979b980-8367-11eb-86eb-5c01fac4b642.jpg)

저도 생각나는대로...

**Comment by EunjinKwon** [comment]
![image](https://user-images.githubusercontent.com/77440874/111033727-03c18480-8456-11eb-9db5-aa8f0b350d41.png)

곧 내용추가 하겠습니다 🙇‍♀️

**Comment by clair-deLune** [comment]
![조성호 - ER](https://user-images.githubusercontent.com/79443607/111055912-ede7aa00-84bd-11eb-9de0-ab0778d6c9a1.jpg)

분류가 미흡 합니다만, 여러분에게 조금이나마 도움이 되고자 admin을 제외한 사용자의 필요한 정보를 추려보았습니다.

**Comment by penglingss** [comment]
다시 그려봤습니다.
### ERD
![Untitled Diagram (4)](https://user-images.githubusercontent.com/56222478/111504494-0fc98100-878b-11eb-9f47-7a702eba37b8.png)

----------------------
### 테이블 스키마
`PK : 밑줄 / FK : 굵은글씨`

- entity -> table

![image](https://user-images.githubusercontent.com/56222478/111505291-d5141880-878b-11eb-9ed8-ac025a4fc589.png)




- relationship -> table

![image](https://user-images.githubusercontent.com/56222478/111505434-f412aa80-878b-11eb-86ea-fdeaa8697fbd.png)

**Comment by rnin9** [comment]
@penglingss 
> ![image](https://user-images.githubusercontent.com/62874963/111555067-edefee80-87ca-11eb-963f-5cfd4b5cbd5c.png)
>> 
>> 1. 빨간 네모 친 두 부분은 겹치기 때문에 하나로 합칠 수 있을것 같습니다. 어제 말씀 드렸던 부분입니다! 
>> 2. 설문조사에 대한 부분이 빠진 것 같습니다. ( 수기로 받는다고 하셨지만, 작성한 것들 저장할 DB는 필요합니다.)
>> 3. 시각화 할 부분에 대한 정의가 필요합니다. 개인적으로는  수강후기에 "취업여부" 컬럼을 만들어서 '취업/미취업'으로 취업 성공 비율을 산정하여 시각화 시키는데 도움을 줄 수 있을 것 같습니다. ( 이외에도  남/여 비율, 나이, 전공자/비전공자, 수강 평점이 시각화에 도움이 될 것 같습니다.)

**Comment by penglingss** [comment]
1. 합치게 되면 후기를 남기기전 일 경우와, 후기를 필수로 남겨야하는게 아닌 이상 null값이 너무 많을것같아서 따로 두는게 좋을것같습니다.
2. 설문 테이블 추가하겠습니다.
3. 통계 말씀하시는걸까요?

**Comment by rnin9** [comment]
@penglingss 
> 1. 합치게 되면 후기를 남기기전 일 경우와, 후기를 필수로 남겨야하는게 아닌 이상 null값이 너무 많을것같아서 따로 두는게 좋을것같습니다.
>> 넵 동의합니다 Table 정의 시 Column에 추가할 부분이 있는지 생각해야 할 것 같습니다. 
> 
> 3. 통계 말씀하시는걸까요?
>> 넵 통계를 이용한 시각화 부분입니다. 보통 SQL로 작성하는 부분인데, 컬럼 부분이 ... 로 다 되어있지않아서 추가 해볼만한 것을 간단히 말씀드려 봤습니다.


추가로 과정 관련으로 궁금한게 있는데, 제가 생각했을때는 다인님이 생각해주신 과정을  ' 강의' ,  '과정' 테이블로 나누어 강의에는  강의에 대한 정보만을 속성으로 담고, 과정에서는 부가적인, 즉 실제로 추진되고, 만들어진 강의만을 담는 테이블로 만들고자 했습니다. 이는 두가지 이유가 있는데

1. 강의인원이 충족되지 않으면 강의를 진행하지 않는다.  ( 설문조사를 통해 계획된 인원만큼이 충족될 시 강의가 열린다고 @rlarhkd 이 알려주셨습니다 이러면 열리지않는 강의들에대한 데이터는 삭제되고, 열릴때마다 작성해주어야 합니다 )  
2. 중첩되고 변경 가능성이 있는 강의속성에 대해 유연하게 대처할 수 있습니다. ex) 합쳐져 있다면 1기교육과정, 2기교육과정, 3기교육과정..... 이런식으로 비슷하지만 미묘하게 다른 인스턴스가 계속 과정 테이블에 들어갈겁니다 

나누는것을 테이블로 구성한다면 이런식이겠네요

|     강의     	| 과정             	|
|:------------:	|:------------------:	|
| 강의코드(PK) 	| 강의코드(FK)(PK) 	|
|    강의명    	| 년도(PK)         	|
| 강사명       	| 기수       	|
| ...          	| 신청 인원              	|
|              	|       ...           	|


그런데 위와같은 방식으로 SQL을 작성했을때, JOIN이 많이 일어나서 합쳐진 데이터를 많이 그리고 자주 뽑아온다면 그냥 다인님 말처럼 '과정'으로 합치는게 나을 수 도 있습니다. 어떻게 생각하시는지 궁금하네요.
